"""Draft evidence for PB governor and Senate candidates (second pass). checks/check_pb2.py re-derives every row."""

ACCESSED = "2026-10-03"


def yt(video, seconds):
    return f"https://www.youtube.com/watch?v={video}&t={seconds}s"


ROWS = [
    {
        "id": "pb2-senador-400-seg-stf-mandato-sofesta-2026-09-15",
        "subject": "senador-400",
        "questionId": "seg-stf-mandato",
        "kind": "platform",
        "position": 1,
        "detail": "Em entrevista à Sofesta FM como candidato ao Senado, defendeu mandato com prazo para ministros do STF.",
        "quote": "eu defendo, por exemplo, que ministro do supremo tenha mandato, tem um período, não pode ser eterno",
        "date": "2026-09-15",
        "source": {"url": yt("yFKgiXsoTaY", 3561), "label": "Sofesta FM, entrevista com João Azevêdo, 14/09/2026, YouTube, 00:59:21, legenda automática"},
        "check": {"video": "yFKgiXsoTaY", "names": ["joão azevêdo", "joao azevedo"],
                  "anchor": "agora, por si só, isso resolve o o problema, a crise instalada na principal corte"},
    },
    {
        "id": "pb2-senador-155-seg-stf-mandato-sofesta-2026-09-18",
        "subject": "senador-155",
        "questionId": "seg-stf-mandato",
        "kind": "platform",
        "position": 1,
        "detail": "Em entrevista à Sofesta FM, defendeu mandatos não vitalícios, de 8 a 12 anos, para ministros de tribunais superiores.",
        "quote": "como também sou defensor de mandatos não vitalícios, mandatos de 8, 10, no máximo, no máximo 12 anos",
        "date": "2026-09-18",
        "source": {"url": yt("ETZSkFyBTSQ", 3649), "label": "Sofesta FM, entrevista com Veneziano Vital, 17/09/2026, YouTube, 01:00:49, legenda automática"},
        "check": {"video": "ETZSkFyBTSQ", "names": ["veneziano"],
                  "anchor": "qual é a proposta que venet teria na na cabeça relativa à questão da indicação"},
    },
    {
        "id": "pb2-senador-222-eco-reforma-tributaria-clickpb-2026-08-21",
        "subject": "senador-222",
        "questionId": "eco-reforma-tributaria",
        "kind": "platform",
        "position": -1,
        "detail": "Na sabatina do ClickPB, criticou a reforma tributária em vigor por criar um IVA alto e disse que o Congresso deveria fazer outra, que reduza impostos.",
        "quote": "fazer uma reforma tributária de verdade que diminui o imposto, não que crie o maior iva do mundo para um governo sedento de imposto",
        "date": "2026-08-21",
        "source": {"url": yt("VpNgBZaAZZI", 2122), "label": "Sabatina ClickPB com Marcelo Queiroga, vídeo publicado em 21/08/2026, YouTube, 00:35:22, legenda automática"},
        "check": {"video": "VpNgBZaAZZI", "names": ["queiroga"],
                  "anchor": "qual será a sua posição no senado sobre esse assunto? candidato, senhor, tem 3 minutos para resposta"},
    },
    {
        "id": "pb2-senador-222-eco-arcabouco-clickpb-2026-08-21",
        "subject": "senador-222",
        "questionId": "eco-arcabouco",
        "kind": "platform",
        "position": -1,
        "detail": "Na sabatina do ClickPB, criticou o fim do teto de gastos e o arcabouço fiscal que o substituiu, dizendo que liberou gastos.",
        "quote": "esse governo acabou com o teto de gastos, foi liberal liberou geral para gastar, né? foi aprovado um tal de um arcaboo fiscal que ele mesmo não compre",
        "date": "2026-08-21",
        "source": {"url": yt("VpNgBZaAZZI", 3739), "label": "Sabatina ClickPB com Marcelo Queiroga, vídeo publicado em 21/08/2026, YouTube, 01:02:19, legenda automática (\"arcaboo\" e \"compre\" como transcritos)"},
        "check": {"video": "VpNgBZaAZZI", "names": ["queiroga"],
                  "anchor": "o que vocês vão fazer ou t feito pela fiscalização da obra da br230"},
    },
    {
        "id": "pb2-senador-222-seg-8-janeiro-arapuan-2026-09-01",
        "subject": "senador-222",
        "questionId": "seg-8-janeiro",
        "kind": "platform",
        "position": 1,
        "detail": "No debate da TV Arapuan, chamou os condenados do 8 de janeiro de vítimas e criticou a Câmara por aprovar a dosimetria em vez de votar a anistia.",
        "quote": "faz um compromisso de pautar o projeto da anistia das vítimas do lá de janeiro de 2023 e aí na hora descumpre o compromisso e no lugar disso aprova lá uma dosimetria",
        "date": "2026-09-01",
        "source": {"url": yt("cAqSz5F2QCo", 9146), "label": "Debate para o Senado, TV Arapuan, 31/08/2026, YouTube, 02:32:26, legenda automática (\"lá de janeiro\" como transcrito)"},
        "check": {"video": "cAqSz5F2QCo", "mode": "debate", "names": ["queiroga"],
                  "selfAnchor": "eu sei, eu conduzi o ministério da saúde numa época muito difícil",
                  "moderatorCue": "candidato marcelo queiroga, por gentileza, se dirige ao seu lugar"},
    },
    {
        "id": "pb2-senador-151-seg-blindagem-sofesta-2026-09-11",
        "subject": "senador-151",
        "questionId": "seg-blindagem",
        "kind": "platform",
        "position": -1,
        "detail": "Em entrevista à Sofesta FM, criticou a PEC da Blindagem, dizendo que ela protegeria parlamentares que cometem crimes.",
        "quote": "e pior foi o o nosso paraibano, deputado federal aqui, colocar a pec da blindagem. quer dizer, quem tiver um mandato pode roubar, pode matar, porque eu tô blindado pel uma pec",
        "date": "2026-09-11",
        "source": {"url": yt("I4aBBPZcRCQ", 5391), "label": "Sofesta FM, entrevista com André Gadelha, 10/09/2026, YouTube, 01:29:51, legenda automática"},
        "check": {"video": "I4aBBPZcRCQ", "names": ["andré gadelha", "andre gadelha"], "anchorWindow": 4500,
                  "anchor": "o fundo partidário com recurso público é o ideal ou deveria ter outra forma"},
    },
    {
        "id": "pb2-senador-272-seg-armas-sofesta-2026-09-09",
        "subject": "senador-272",
        "questionId": "seg-armas",
        "kind": "platform",
        "position": 1,
        "detail": "Em entrevista à Sofesta FM, perguntado sobre armas nas famílias, disse ser totalmente a favor do armamento, com um estudo melhor de viabilidade.",
        "quote": "eu sou totalmente a favor do armamento, mas que existe e precisa ter uma um estudo melhor de viabilidade desse projeto",
        "date": "2026-09-09",
        "source": {"url": yt("P9LHDt2bMcs", 1004), "label": "Sofesta FM, entrevista com Rinaldo Júnior, 08/09/2026, YouTube, 00:16:44, legenda automática"},
        "check": {"video": "P9LHDt2bMcs", "names": ["rinaldo júnior", "rinaldo junior"],
                  "anchor": "como é que você entende essa questão da utilização de armas dentro das famílias"},
    },
]
