export const COPY = {
  appName: 'Cola Eleitoral',
  credits: { madeBy: 'feito por lucasmsa', coffee: 'me paga um café ☕', source: 'código-fonte', github: 'Código-fonte no GitHub' },
  home: {
    replayCover: 'Ver de novo',
    lead: 'Diga o que você pensa sobre temas que o Congresso e os candidatos já enfrentaram. O app compara suas respostas com votos registrados e planos de governo e, no fim, monta a sua cola para o 1º turno.',
    privacy: 'Suas respostas ficam só neste navegador. Nada é enviado para servidor nenhum.',
    trail: 'Trilha de lições',
    start: 'Começar',
    resume: 'Continuar',
    redo: 'Rever',
    results: 'Ver seu resultado',
    allDone: 'Você respondeu todas as lições. O resultado está pronto.',
    review: 'Quiz',
    reviewHint: 'Teste o que você sabe sobre os candidatos principais: votos, propostas e trajetória.',
    cola: 'Minha cola',
    colaHint: 'Os números para levar no papel, na ordem da urna.',
    resultsHint: 'Seu alinhamento, quem concorda mais com você e o perfil dos principais candidatos.',
  },
  lesson: {
    back: 'Voltar',
    backToLast: 'Voltar à última pergunta',
    ask: 'Você concorda?',
    askScale: 'Qual destas posições está mais perto da sua?',
    importance: 'Quanto isso pesa no seu voto?',
    dontKnow: 'Não sei',
    confirm: 'Confirmar',
    nextQuestion: 'Próxima pergunta',
    finish: 'Terminar lição',
    stamp: 'Registrado',
    stampSkip: 'Não sei',
    recorded: 'Resposta registrada.',
    recordedSkip: 'Anotado: esta pergunta fica fora da conta.',
    recordedHint:
      'As posições dos candidatos ficam guardadas para o fim. Assim elas não influenciam as suas próximas respostas.',
    exit: 'Sair da lição',
    doneTitle: 'Lição concluída',
    doneBody: 'Suas respostas já entram nos resultados. Você pode mudar o peso de cada pergunta lá.',
    nextUnit: 'Próxima lição',
    toResults: 'Ver seu resultado',
    home: 'Voltar ao início',
  },
  explainer: {
    title: 'Entenda antes de responder',
    openHint: 'abrir',
    pending: 'A explicação detalhada desta pergunta ainda está em checagem. Por enquanto, este é o contexto da votação.',
  },
  fact: {
    lowDiscrimination: 'Quase todos votaram igual nesta votação, então ela diferencia pouco os candidatos.',
    source: 'Fonte',
  },
  result: {
    title: 'Seu resultado',
    kicker: (n: number) => `com base em ${n} ${n === 1 ? 'resposta' : 'respostas'}`,
    stepsLabel: 'Etapas do resultado',
    prev: 'Voltar',
    next: 'Seguir',
    toCola: 'Montar minha cola',
  },
  restart: {
    button: 'Recomeçar o quiz do zero',
    question: 'Isso apaga todas as suas respostas e a sua cola neste navegador. Quer mesmo recomeçar?',
    confirm: 'Sim, apagar e recomeçar',
    cancel: 'Cancelar',
  },
  alignment: {
    lead:
      'Aqui você se vê ao lado de políticos, partidos e países, usando só posições checadas: votos, atos de governo, planos registrados e leis em vigor. Cada ponto resume as posições em perguntas daquele eixo, puxado para o centro quando há poucas.',
    noAxes: 'O método dos eixos ainda está em checagem. Enquanto isso, veja abaixo quem mais concorda com você.',
    chartTitle: 'Gráfico de alinhamento',
    chartLabel: 'Gráfico com dois eixos: econômico na horizontal e de costumes na vertical',
    filters: 'Mostrar no gráfico',
    hint: 'Passe o mouse ou o foco num ponto para ver quantas perguntas sustentam a posição dele.',
    focused: (label: string, detail: string, nx: number, ny: number) =>
      `${label} (${detail}): eixo econômico com ${nx} ${nx === 1 ? 'pergunta' : 'perguntas'}, eixo de costumes com ${ny} ${ny === 1 ? 'pergunta' : 'perguntas'}.`,
    dotLabel: (label: string, nx: number, ny: number) => `${label}: ${nx} perguntas no eixo econômico, ${ny} no de costumes`,
    legend: 'Estrela: você. Círculo: político. Quadrado: partido ou federação. Losango: país.',
    hidden: (parts: string[], min: number) =>
      `Não aparecem no gráfico por ter menos de ${min} perguntas checadas num eixo: ${parts.join(', ').replace(/, ([^,]*)$/, ' e $1')}. Eles continuam na lista abaixo quando têm 3 perguntas em comum com você.`,
    kindCount: (kind: 'politico' | 'partido' | 'pais', n: number) =>
      ({ politico: n === 1 ? '1 político' : `${n} políticos`, partido: n === 1 ? '1 partido ou federação' : `${n} partidos e federações`, pais: n === 1 ? '1 país' : `${n} países` })[kind],
    youHiddenTitle: 'Termine de responder antes de ver seu alinhamento.',
    youHidden: (needX: number, needY: number) => {
      const parts = [
        needX > 0 ? `${needX} ${needX === 1 ? 'resposta' : 'respostas'} no eixo econômico` : '',
        needY > 0 ? `${needY} ${needY === 1 ? 'resposta' : 'respostas'} no de costumes` : '',
      ].filter(Boolean);
      return `Para você aparecer no gráfico, ${parts.length > 1 ? 'faltam' : needX + needY === 1 ? 'falta' : 'faltam'} ${parts.join(' e ')}.`;
    },
    keepAnswering: 'Continuar respondendo',
    methodTitle: 'Como calculamos',
    methodTag: 'método',
    methodBody: (min: number) => [
      'Cada pergunta foi ligada a um eixo, com uma direção: concordar com a frase puxa para um dos polos. Essa ligação é uma escolha de método, explicada abaixo pergunta por pergunta. Ela não é um fato sobre ninguém.',
      `A posição de cada pessoa, partido ou país em um eixo vem das posições checadas nas perguntas daquele eixo. Quem tem menos de ${min} perguntas em um eixo não aparece no gráfico.`,
      'Para não exagerar quem tem poucas posições checadas, cada eixo conta como se tivesse mais 2 respostas neutras; com muitas posições na mesma direção, o ponto se aproxima da borda.',
      'Os eixos resumem muito. Duas pessoas no mesmo ponto podem discordar em temas que nenhuma pergunta cobre.',
    ],
    noAxisRows: 'Nenhuma pergunta ligada a este eixo.',
    listsTitle: 'Mais alinhados com você',
    listsExplain:
      'A porcentagem é a concordância média nas perguntas que vocês dois têm em comum, pesada pelo quanto cada uma pesa no seu voto. Só entra quem tem pelo menos 3 perguntas em comum com você.',
    noneYet: 'Ainda não há perguntas em comum suficientes.',
    common: (n: number) => `${n} ${n === 1 ? 'pergunta' : 'perguntas'} em comum`,
  },
  profile: {
    title: 'Conheça os 5 principais',
    titleList: (list: string) => `5 nomes de ${list}`,
    explain: 'Ordem pela intenção de voto nas pesquisas checadas, quando houver. Cada frase vem com a fonte.',
    explainUnranked: 'Não há pesquisa checada para este cargo, então a ordem não indica favoritismo. Cada frase vem com a fonte.',
    none: 'Os perfis deste cargo ainda estão em checagem.',
    rank: (n: number) => `${n}º`,
    notice: 'deixou a disputa',
    presents: 'Como se apresenta',
    experience: 'Experiência',
    proposals: 'Principais propostas',
    proposalsShort: 'Propostas',
    defendsShort: 'O que defende',
    controversies: 'Polêmicas',
    noControversy: 'Nada documentado nas fontes consultadas.',
    response: 'Resposta do candidato',
    source: 'fonte',
    more: (n: number) => `ver mais (${n})`,
    sectionsLabel: (name: string) => `Seções do perfil de ${name}`,
    defends: 'O que defende, segundo votos e declarações',
  },
  results: {
    ranking: 'Quem concorda mais com você',
    showRest: (n: number) => `Ver os outros ${n}`,
    howToRead: 'Como ler a porcentagem',
    explain:
      'A porcentagem diz o quanto as posições registradas de cada um concordam com as suas, contando só as perguntas que têm evidência checada. A faixa mostra até onde a nota poderia ir se as perguntas sem evidência fossem todas contra você (ponta esquerda) ou todas a seu favor (ponta direita). Não é previsão de voto nem nota de qualidade do candidato.',
    noAnswers: 'Responda pelo menos uma lição para ver resultados.',
    weightsTitle: 'Peso das evidências',
    weightsExplain:
      'Registro é o que a pessoa fez: votos, sanções e vetos. Declaração é o que ela disse: plano de governo e entrevistas. Quem não tem registro é avaliado só pela declaração.',
    record: 'Registro',
    platform: 'Declaração',
    unscored: 'Sem evidência checada para as suas respostas',
    unscoredExplain: 'Não dá para comparar estas pessoas com você ainda. Isso não quer dizer que discordam.',
    listsTitle: 'Primeiro, o partido ou a federação',
    listsExplain:
      'Para deputado, o voto conta primeiro para o partido ou federação, que define quantas cadeiras leva. Por isso a comparação começa pelas listas, usando a orientação das lideranças na Câmara, e depois passa para as pessoas da lista escolhida.',
    peopleIn: (list: string) => `Candidatos de ${list}`,
    chooseList: 'Ver candidatos',
    backToLists: 'Voltar para as listas',
    putInCola: 'Pôr na cola',
    inCola: (slot: string) => `Na cola (${slot})`,
    remove: 'Tirar',
    slotsFull: 'As vagas deste cargo já estão na cola',
    legendaTitle: (list: string) => `Voto de legenda em ${list}`,
    legendaExplain:
      'Na legenda você digita só os 2 números de um partido. O voto vai para o partido, e dentro de uma federação, para a federação.',
    cancel: 'Cancelar',
    thin: 'pouca evidência',
    coverage: (n: number, m: number) => `${n} de ${m} ${m === 1 ? 'pergunta' : 'perguntas'} com evidência`,
    details: 'Ver por quê',
  },
  detail: {
    close: 'Fechar',
    you: 'Você',
    them: 'Posição',
    weight: 'Peso',
    plan: 'Plano de governo registrado no TSE (PDF)',
    elected: 'Eleições vencidas, segundo o histórico do TSE',
    mates: 'Chapa',
    status: 'Situação no TSE',
    noRows: 'Nenhuma pergunta deste cargo.',
  },
  polls: {
    title: 'Pesquisas (não entram na conta)',
    explain:
      'Mostram a intenção de voto de uma amostra de eleitores em datas passadas, dentro de uma margem de erro. Não dizem nada sobre quem concorda com você. Os números foram conferidos na reportagem citada.',
    pressChecked: 'conferido na imprensa',
    none: 'Nenhuma pesquisa checada para este cargo.',
  },
  review: {
    nav: 'Quiz',
    title: 'Quiz: quem defende o quê',
    intro:
      'Teste o que você aprendeu sobre os candidatos antes de votar: como votaram, o que propõem, o que já fizeram. Cada resposta mostra a fonte.',
    scope: 'As perguntas são sobre os 5 principais candidatos a presidente, governador e senador, os mesmos dos perfis do resultado.',
    count: (n: number) => `${n} perguntas`,
    start: 'Começar o quiz',
    exit: 'Sair do quiz',
    correct: 'Isso mesmo.',
    wrong: 'Não foi isso.',
    next: 'Próxima',
    finish: 'Ver pontuação',
    doneTitle: 'Fim do quiz',
    doneBody: (hits: number, total: number) => `Você acertou ${hits} de ${total}.`,
    reviewMistakes: (n: number) => `Revisar erros (${n})`,
    noMistakes: 'Nenhum erro nesta rodada.',
    mistakesTitle: 'Seus erros',
    yourPick: 'Você marcou',
    rightAnswer: 'Resposta certa',
    backToScore: 'Voltar à pontuação',
    toCola: 'Ir para a cola',
    again: 'Fazer outra rodada',
    home: 'Voltar ao início',
    empty: 'Ainda não há fatos checados suficientes sobre os candidatos principais para montar o quiz.',
  },
  cola: {
    title: 'Minha cola',
    lead: 'Os votos aparecem na ordem em que a urna pede. Imprima, recorte e leve na carteira.',
    rules: 'A cola em papel é permitida. O celular fica fora da cabine.',
    type: 'Digite o número',
    branco: 'Branco',
    clear: 'Limpar',
    print: 'Imprimir',
    printHint: 'Saem duas cópias no tamanho de um cartão (85,6 × 54 mm).',
    notFound: 'Número não encontrado para este cargo',
    incomplete: (n: number) => `Faltam dígitos: este cargo tem ${n}`,
    legenda: (party: string) => `Legenda do ${party}`,
    brancoLabel: 'Voto em branco',
    empty: 'Em aberto',
    sameSenator: 'O mesmo número está nas duas vagas de senador. Escolha duas pessoas diferentes.',
    toResults: 'Escolher pelos resultados',
    cardTitle: 'MINHA COLA, 4 DE OUTUBRO',
    cardPlace: 'Paraíba',
  },
  round2: {
    kicker: (date: string) => `2º turno, ${date}`,
    versus: (a: string, b: string) => `${a} x ${b}`,
    firstRound: (br: string, pb: string) => `1º turno: ${br}% dos votos válidos no Brasil, ${pb}% na Paraíba`,
    governorDecided: (name: string, pct: string) =>
      `Governador da Paraíba decidido no 1º turno: ${name}, eleito com ${pct}% dos votos válidos.`,
    compare: 'Comparar com as suas respostas',
    lead: 'A comparação usa as respostas que você já deu, sem perguntar de novo. A conta é a mesma do 1º turno: só entram votos, atos e declarações checados.',
    agree: 'concordância com você',
    noScore: 'Ainda sem perguntas em comum com você',
    nudgeTitle: (n: number) => `Faltam ${n} ${n === 1 ? 'pergunta' : 'perguntas'} em que pelo menos um dos dois tem posição checada.`,
    nudgeBody: 'Responda essas para a comparação ficar mais justa. As perguntas em que os dois têm posição aparecem primeiro.',
    nudgeCta: 'Responder as que faltam',
    allAnswered: 'Você já respondeu todas as perguntas em que eles têm posição checada.',
    byQuestion: 'Pergunta por pergunta',
    byQuestionLead: 'Só aparecem perguntas em que pelo menos um dos dois tem posição checada.',
    you: 'Você',
    youSkipped: 'pulou esta pergunta',
    youMissing: 'ainda não respondeu',
    noPosition: 'sem posição checada',
    sources: (n: number) => `ver ${n === 1 ? 'a fonte' : `as ${n} fontes`}`,
    toProfiles: 'Perfis e polêmicas dos dois',
    toAlignment: 'Ver o gráfico de alinhamento',
    resultsSource: 'Resultado oficial do 1º turno',
    colaTitle: 'Cola do 2º turno',
    colaLead: (numbers: string) =>
      `No 2º turno, a Paraíba só vota para presidente, porque o governador foi eleito no 1º turno. Os números possíveis são ${numbers}.`,
    cardTitle: (date: string) => `MINHA COLA, ${date.toLocaleUpperCase('pt-BR')}`,
    cardNote: (name: string) => `Governador eleito no 1º turno: ${name}. Nesta votação, só presidente.`,
    notFinalist: (numbers: string) => `Este número não está no 2º turno. Os números são ${numbers}.`,
  },
  footer: (n: number, date: string) =>
    `${n} fatos checados em fonte primária (TSE, Câmara, Senado, Planalto e planos de governo registrados). Dados de ${date}.`,
};
