"""Country stances. Each row: (country, questionId, position, detail pt-BR, url, support snippet, source label)."""

C = "https://www.constituteproject.org/constitution"
CRT = "Constituição, via Constitute Project"

ROWS = [
    # soc-aborto: "O aborto deve deixar de ser crime nas primeiras 12 semanas de gestação."
    ("Uruguai", "soc-aborto", 1, "A Lei 18.987/2012 afasta os crimes de aborto do Código Penal quando a interrupção é feita nas primeiras 12 semanas, cumpridos requisitos como a consulta médica prévia.",
     "https://www.impo.com.uy/bases/leyes/18987-2012", "se realice durante las primeras doce semanas de gravidez", "IMPO, Lei 18.987/2012",
     ["la mujer deberá acudir a consulta médica"]),
    ("Argentina", "soc-aborto", 1, "A Lei 27.610/2020 garante o aborto a pedido até a 14ª semana.",
     "https://servicios.infoleg.gob.ar/infolegInternet/anexos/345000-349999/346231/norma.htm",
     "acceder a la interrupción de su embarazo hasta la semana catorce (14), inclusive", "InfoLEG, Lei 27.610/2020"),
    ("Chile", "soc-aborto", -1, "A Lei 21.030/2017 permite o aborto só em três situações: risco de vida, feto inviável e estupro.",
     "https://nuevo.leychile.cl/servicios/Navegar/get_norma_json?idNorma=1108237",
     "sea resultado de una violación, siempre que no hayan transcurrido más de doce semanas de gestación", "BCN LeyChile, Lei 21.030/2017",
     ["la mujer se encuentre en riesgo vital", "incompatible con la vida extrauterina independiente"]),
    ("Colômbia", "soc-aborto", 1, "A Corte Constitucional (Sentença C-055/2022) decidiu que o aborto não é crime até a 24ª semana.",
     "https://www.corteconstitucional.gov.co/comunicados/Comunicado%20de%20prensa%20Sentencia%20C-055-22%20-%20Febrero%2021-22.pdf",
     "no se configura el delito cuando la conducta se practique antes de la semana 24 de gestación", "Corte Constitucional, comunicado da Sentença C-055/2022"),
    ("EUA", "soc-aborto", 0, "Desde Dobbs (2022), a Suprema Corte deixou a regra para cada estado; há estados que proíbem e outros que permitem.",
     "https://www.supremecourt.gov/opinions/21pdf/19-1392_6j37.pdf",
     "the authority to regulate abortion is returned to the people and their elected representatives", "Suprema Corte dos EUA, Dobbs v. Jackson (2022)"),
    ("Portugal", "soc-aborto", 1, "O Código Penal (art. 142, redação da Lei 16/2007) não pune o aborto feito por opção da mulher até a 10ª semana.",
     "https://www.pgdlisboa.pt/leis/lei_mostra_articulado.php?artigo_id=109A0142&nid=109&tabela=leis&pagina=1&ficha=1&so_miolo=&nversao=",
     "por opção da mulher, nas primeiras 10 semanas de gravidez", "PGD Lisboa, Código Penal, art. 142"),
    ("Espanha", "soc-aborto", 1, "A Lei Orgânica 2/2010 (art. 14) permite o aborto a pedido nas primeiras 14 semanas.",
     "https://www.boe.es/buscar/act.php?id=BOE-A-2010-3514",
     "podrá interrumpirse el embarazo dentro de las primeras catorce semanas de gestación a petición de la mujer embarazada", "BOE, Lei Orgânica 2/2010"),
    ("França", "soc-aborto", 1, "Desde 2024 a Constituição (art. 34) garante a liberdade de interromper a gravidez, nos termos da lei.",
     f"{C}/France_2024?lang=en", "the woman's guaranteed freedom to have a voluntary interruption of pregnancy", f"{CRT}, França 2024"),
    ("Alemanha", "soc-aborto", 1, "O Código Penal (§ 218a) não considera crime o aborto até 12 semanas após a concepção, com aconselhamento obrigatório pelo menos 3 dias antes.",
     "https://www.gesetze-im-internet.de/stgb/__218a.html", "seit der empfängnis nicht mehr als zwölf wochen vergangen sind", "Gesetze im Internet, StGB § 218a",
     ["der tatbestand des § 218 ist nicht verwirklicht", "mindestens drei tage vor dem eingriff hat beraten lassen"]),
    ("Suécia", "soc-aborto", 1, "A Lei do Aborto (1974:595) permite o aborto a pedido até o fim da 18ª semana.",
     "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/abortlag-1974595_sfs-1974-595/",
     "får abort utföras om åtgärden vidtas före utgången av artonde havandeskapsveckan", "Riksdagen, Abortlag (1974:595)"),
    ("Rússia", "soc-aborto", 1, "A Lei Federal 323-FZ (art. 56) permite o aborto a pedido até a 12ª semana.",
     "https://www.consultant.ru/document/cons_doc_LAW_121895/5e5a1acccfe61df97f5fcb684e12cab5fee05e25/",
     "искусственное прерывание беременности по желанию женщины проводится при сроке беременности до двенадцати недель", "ConsultantPlus, Lei Federal 323-FZ, art. 56"),
    ("Índia", "soc-aborto", 0, "A Lei MTP (emenda de 2021) permite o aborto até a 20ª semana com aval médico e por motivos definidos em lei, como falha de método contraceptivo.",
     "https://egazette.gov.in/WriteReadData/2021/226130.pdf", "where the length of the pregnancy does not exceed twenty weeks", "Gazette of India, MTP (Amendment) Act 2021",
     ["failure of any device or method used by any woman or her partner"]),

    # seg-stf-mandato: "Ministros do STF devem ter mandato com prazo fixo, em vez de cargo vitalício."
    ("Espanha", "seg-stf-mandato", 1, "Os juízes do Tribunal Constitucional têm mandato de 9 anos (Constituição, art. 159).",
     f"{C}/Spain_2011?lang=en", "members of the constitutional court shall be appointed for a period of nine years", f"{CRT}, Espanha"),
    ("Portugal", "seg-stf-mandato", 1, "Os juízes do Tribunal Constitucional têm mandato de 9 anos, sem renovação (Constituição, art. 222).",
     f"{C}/Portugal_2005?lang=en", "the term of office of judge of the constitutional court shall be nine years and shall not be renewable", f"{CRT}, Portugal"),
    ("França", "seg-stf-mandato", 1, "Os membros do Conselho Constitucional têm mandato de 9 anos, sem renovação (Constituição, art. 56).",
     f"{C}/France_2024?lang=en", "each of whom shall hold office for a non-renewable term of nine years", f"{CRT}, França 2024"),
    ("Chile", "seg-stf-mandato", 1, "Os ministros do Tribunal Constitucional têm mandato de 9 anos (Constituição, art. 92).",
     f"{C}/Chile_2021?lang=en", "its members shall last nine years in office", f"{CRT}, Chile"),
    ("Colômbia", "seg-stf-mandato", 1, "Os magistrados da Corte Constitucional têm mandato único de 8 anos (Constituição, art. 239).",
     f"{C}/Colombia_2015?lang=en", "the judges of the constitutional court shall be elected by the senate of the republic for single terms of eight years", f"{CRT}, Colômbia"),
    ("Uruguai", "seg-stf-mandato", 1, "Os ministros da Suprema Corte de Justiça têm mandato de 10 anos (Constituição, art. 237).",
     f"{C}/Uruguay_2004?lang=en", "the members of the supreme court of justice shall serve for ten years", f"{CRT}, Uruguai"),
    ("Alemanha", "seg-stf-mandato", 1, "Os juízes do Tribunal Constitucional Federal têm mandato de 12 anos, sem reeleição (BVerfGG, § 4).",
     "https://www.gesetze-im-internet.de/bverfgg/__4.html", "die amtszeit der richter dauert zwölf jahre", "Gesetze im Internet, BVerfGG § 4",
     ["eine anschließende oder spätere wiederwahl der richter ist ausgeschlossen"]),
    ("Argentina", "seg-stf-mandato", -1, "Os juízes da Suprema Corte ficam no cargo enquanto tiverem boa conduta; aos 75 anos precisam de nova nomeação (Constituição, arts. 99 e 110).",
     f"{C}/Argentina_1994?lang=en", "shall hold their offices during their good behavior", f"{CRT}, Argentina",
     ["once they attain the age of seventy-five"]),
    ("EUA", "seg-stf-mandato", -1, "Os juízes da Suprema Corte são vitalícios enquanto tiverem boa conduta (Constituição, art. III).",
     f"{C}/United_States_of_America_1992?lang=en", "the judges, both of the supreme and inferior courts, shall hold their offices during good behaviour", f"{CRT}, EUA"),
    ("Índia", "seg-stf-mandato", -1, "Os juízes da Suprema Corte ficam no cargo até os 65 anos (Constituição, art. 124).",
     f"{C}/India_2023?lang=en", "shall hold office until he attains the age of sixty-five years", f"{CRT}, Índia"),
    ("Japão", "seg-stf-mandato", -1, "Os juízes da Suprema Corte ficam até a idade de aposentadoria fixada em lei, com revisão popular nas eleições (Constituição, art. 79).",
     f"{C}/Japan_1946?lang=en", "the judges of the supreme court shall be retired upon the attainment of the age as fixed by law", f"{CRT}, Japão",
     ["the appointment of the judges of the supreme court shall be reviewed by the people"]),
    ("Canadá", "seg-stf-mandato", -1, "Os juízes da Suprema Corte deixam o cargo aos 75 anos, sem prazo fixo (Supreme Court Act, s. 9).",
     "https://laws-lois.justice.gc.ca/eng/acts/s-26/page-1.html", "a judge shall cease to hold office on attaining the age of seventy-five years", "Justice Laws, Supreme Court Act"),
    ("Suécia", "seg-stf-mandato", -1, "Juízes efetivos só deixam o cargo por falta grave ou aposentadoria (Instrumento de Governo, cap. 11, art. 7).",
     f"{C}/Sweden_2012?lang=en", "he or she has reached the applicable retirement age", f"{CRT}, Suécia",
     ["a person who has been appointed a permanent salaried judge may be removed from office only if"]),
    ("Rússia", "seg-stf-mandato", -1, "Os juízes do Tribunal Constitucional não têm prazo de mandato; o limite é a idade de 70 anos (Lei Constitucional Federal 1-FKZ, art. 12).",
     "https://www.consultant.ru/document/cons_doc_LAW_4172/3663587b424165f21b75863c808d15ab44bc5ff0/",
     "полномочия судьи конституционного суда российской федерации не ограничены определенным сроком", "ConsultantPlus, 1-FKZ, art. 12",
     ["предельный возраст пребывания в должности судьи конституционного суда российской федерации - семьдесят лет"]),
    ("China", "seg-stf-mandato", 0, "Só o presidente da Suprema Corte Popular tem mandato fixo na Constituição: o mesmo da Assembleia, com no máximo dois seguidos (art. 129).",
     f"{C}/China_2018?lang=en", "the term of office of the president of the supreme people's court is the same as that of the national people's congress; he shall serve no more than two consecutive terms", f"{CRT}, China"),

    # eco-bc-autonomo: "O Banco Central deve ter autonomia formal, com mandato fixo para seus diretores."
    ("Chile", "eco-bc-autonomo", 1, "A Constituição (art. 108) cria o Banco Central como órgão autônomo, de caráter técnico.",
     f"{C}/Chile_2021?lang=en", "there shall be an autonomous body, with its own patrimony, of a technical nature, called central bank", f"{CRT}, Chile"),
    ("Colômbia", "eco-bc-autonomo", 1, "A Constituição (art. 371) dá ao Banco da República autonomia administrativa, patrimonial e técnica.",
     f"{C}/Colombia_2015?lang=en", "with administrative, patrimonial, and technical autonomy", f"{CRT}, Colômbia"),
    ("México", "eco-bc-autonomo", 1, "A Constituição (art. 28) determina um banco central autônomo em suas funções e administração.",
     f"{C}/Mexico_2015?lang=en", "the state shall have a central bank that shall be autonomous in the exercise of its functions and its administration", f"{CRT}, México"),
    ("Uruguai", "eco-bc-autonomo", 1, "A Carta Orgânica (Lei 16.696, art. 1) define o Banco Central como ente autônomo, com autonomia técnica, administrativa e financeira.",
     "https://www.impo.com.uy/bases/leyes/16696-1995", "es un ente autónomo y dotado de autonomía técnica, administrativa y financiera", "IMPO, Lei 16.696/1995"),
    ("Argentina", "eco-bc-autonomo", 1, "A Carta Orgânica (Lei 24.144) define o BCRA como entidade autárquica, com presidente e diretores de mandato de 6 anos.",
     "https://servicios.infoleg.gob.ar/infolegInternet/anexos/0-4999/542/norma.htm", "durarán seis (6) años en sus funciones", "InfoLEG, Lei 24.144",
     ["es una entidad autárquica del estado nacional"]),
    ("EUA", "eco-bc-autonomo", 1, "Os diretores do Federal Reserve têm mandato de 14 anos (Federal Reserve Act, seção 10).",
     "https://www.federalreserve.gov/aboutthefed/section10.htm", "for terms of fourteen years", "Federal Reserve, Federal Reserve Act, seção 10"),
    ("Canadá", "eco-bc-autonomo", 0, "O presidente do Banco do Canadá tem mandato de 7 anos, mas o ministro pode dar uma ordem escrita sobre política monetária (Bank of Canada Act, s. 14).",
     "https://laws-lois.justice.gc.ca/eng/acts/b-2/page-2.html", "give to the governor a written directive concerning monetary policy", "Justice Laws, Bank of Canada Act",
     [("https://laws-lois.justice.gc.ca/eng/acts/b-2/page-1.html", "shall each be appointed for a term of seven years")]),
    ("Espanha", "eco-bc-autonomo", 1, "O Banco de Espanha atua com autonomia em relação à administração do Estado, e o presidente tem mandato de 6 anos sem renovação (Lei 13/1994, arts. 1 e 25).",
     "https://www.boe.es/buscar/act.php?id=BOE-A-1994-12553", "actuará con autonomía respecto a la administración general del estado", "BOE, Lei 13/1994",
     ["el mandato de gobernador y subgobernador tendrá una duración de seis años, sin posible renovación"]),
    ("Alemanha", "eco-bc-autonomo", 1, "A Lei Fundamental (art. 88) admite transferir as funções do Bundesbank ao Banco Central Europeu, que é independente.",
     f"{C}/German_Federal_Republic_2014?lang=en", "the european central bank, which is independent", f"{CRT}, Alemanha"),
    ("Suécia", "eco-bc-autonomo", 1, "Pelo Instrumento de Governo (cap. 9, art. 13), nenhuma autoridade pode determinar como o Riksbank decide a política monetária.",
     f"{C}/Sweden_2012?lang=en", "no public authority may determine how the riksbank shall decide in matters of monetary policy", f"{CRT}, Suécia"),
    ("Rússia", "eco-bc-autonomo", 1, "A Constituição (art. 75) manda o Banco Central proteger o rublo de forma independente dos outros órgãos do Estado.",
     f"{C}/Russia_2014?lang=en", "which it shall fulfil independently of other state governmental bodies", f"{CRT}, Rússia"),

    # seg-drogas: "Portar droga em qualquer quantidade deve ser crime previsto na Constituição."
    ("Argentina", "seg-drogas", 1, "A Lei 23.737 (art. 14) pune com 1 mês a 2 anos de prisão a posse de pouca droga para uso pessoal.",
     "https://servicios.infoleg.gob.ar/infolegInternet/anexos/0-4999/138/texact.htm",
     "la pena será de un mes a dos años de prisión cuando, por su escasa cantidad y demás circunstancias, surgiere inequívocamente que la tenencia es para uso personal", "InfoLEG, Lei 23.737"),
    ("Chile", "seg-drogas", 0, "A Lei 20.000 (art. 4) não aplica a pena de prisão a quem justifica que a droga é para uso pessoal exclusivo e próximo no tempo.",
     "https://nuevo.leychile.cl/servicios/Navegar/get_norma_json?idNorma=235507",
     "a menos que justifique que están destinadas a la atención de un tratamiento médico o a su uso o consumo personal exclusivo y próximo en el tiempo", "BCN LeyChile, Lei 20.000"),
    ("Espanha", "seg-drogas", -1, "Consumir ou portar droga em lugar público é infração administrativa grave, não crime (Lei Orgânica 4/2015, de segurança cidadã, art. 36, item 16).",
     "https://www.boe.es/buscar/act.php?id=BOE-A-2015-3442",
     "el consumo o la tenencia ilícitos de drogas tóxicas, estupefacientes o sustancias psicotrópicas, aunque no estuvieran destinadas al tráfico, en lugares, vías, establecimientos públicos", "BOE, Lei Orgânica 4/2015"),
    ("Alemanha", "seg-drogas", 0, "A lei (BtMG § 29) pune a posse de drogas sem autorização, mas o tribunal pode deixar de punir quando é pouca quantidade para uso próprio.",
     "https://www.gesetze-im-internet.de/btmg_1981/__29.html", "betäubungsmittel besitzt, ohne zugleich im besitz einer schriftlichen erlaubnis für den erwerb zu sein", "Gesetze im Internet, BtMG § 29",
     ["lediglich zum eigenverbrauch in geringer menge"]),
    ("Suécia", "seg-drogas", 1, "A Lei Penal de Drogas (1968:64, art. 1) pune com até 3 anos de prisão quem possui ou usa droga.",
     "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/narkotikastrafflag-196864_sfs-1968-64/",
     "innehar, brukar eller tar annan befattning med narkotika döms för narkotikabrott till fängelse i högst tre år", "Riksdagen, Narkotikastrafflag (1968:64)"),
    ("EUA", "seg-drogas", 1, "Pela lei federal (21 U.S.C. § 844), possuir substância controlada sem receita é crime.",
     "https://www.law.cornell.edu/uscode/text/21/844",
     "it shall be unlawful for any person knowingly or intentionally to possess a controlled substance unless such substance was obtained directly, or pursuant to a valid prescription", "Cornell LII, 21 U.S.C. § 844"),
    ("Canadá", "seg-drogas", 0, "A lei proíbe a posse das drogas das listas I a III (CDSA, s. 4), mas a maconha é legal para adultos até 30 g em público (Cannabis Act, s. 8).",
     "https://laws-lois.justice.gc.ca/eng/acts/c-38.8/page-1.html", "no person shall possess a substance included in schedule i, ii or iii", "Justice Laws, CDSA",
     [("https://laws-lois.justice.gc.ca/eng/acts/c-24.5/page-1.html", "for an individual who is 18 years of age or older to possess, in a public place, cannabis of one or more classes of cannabis the total amount of which, as determined in accordance with schedule 3, is equivalent to more than 30 g of dried cannabis")]),
    ("Colômbia", "seg-drogas", 0, "A Constituição (art. 49) proíbe portar e consumir drogas sem receita médica e manda a lei prever, para usuários, medidas administrativas e tratamento.",
     f"{C}/Colombia_2015?lang=en", "the possession and the consumption of narcotic and psychoactive drugs is prohibited, except for medical prescription", f"{CRT}, Colômbia",
     ["an act shall establish administrative measures and treatments of a pedagogic, prophylactic and therapeutical character for persons consuming these subs"]),

    # eco-6x1: "A escala 6x1 deve acabar, com jornada de até 40 horas e dois dias de descanso por semana, sem redução de salário."
    ("Portugal", "eco-6x1", 1, "O Código do Trabalho (art. 203) limita o período normal a 8 horas por dia e 40 horas por semana.",
     "https://www.pgdlisboa.pt/leis/lei_mostra_articulado.php?artigo_id=1047A0203&nid=1047&tabela=leis&pagina=1&ficha=1&so_miolo=&nversao=",
     "o período normal de trabalho não pode exceder oito horas por dia e quarenta horas por semana", "PGD Lisboa, Código do Trabalho, art. 203"),
    ("Espanha", "eco-6x1", 1, "O Estatuto dos Trabalhadores (art. 34) limita a jornada a 40 horas semanais em média anual.",
     "https://www.boe.es/buscar/act.php?id=BOE-A-2015-11430",
     "la duración máxima de la jornada ordinaria de trabajo será de cuarenta horas semanales de trabajo efectivo de promedio en cómputo anual", "BOE, Estatuto dos Trabalhadores"),
    ("Suécia", "eco-6x1", 1, "A Lei da Jornada (1982:673, § 5) limita a jornada ordinária a 40 horas por semana.",
     "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/arbetstidslag-1982673_sfs-1982-673/",
     "den ordinarie arbetstiden får uppgå till högst 40 timmar i veckan", "Riksdagen, Arbetstidslag (1982:673)"),
    ("Rússia", "eco-6x1", 1, "O Código do Trabalho (art. 91) limita a jornada normal a 40 horas por semana.",
     "https://www.consultant.ru/document/cons_doc_LAW_34683/bd14cccf0a1f074ef104e82522f7e2dea04d651f/",
     "нормальная продолжительность рабочего времени не может превышать 40 часов в неделю", "ConsultantPlus, Código do Trabalho, art. 91"),
    ("EUA", "eco-6x1", 0, "A lei federal (FLSA, 29 U.S.C. § 207) não proíbe passar de 40 horas por semana, mas exige pagar hora extra com 50% a mais acima disso.",
     "https://www.law.cornell.edu/uscode/text/29/207",
     "for a workweek longer than forty hours unless such employee receives compensation for his employment in excess of the hours above specified at a rate not less than one and one-half times", "Cornell LII, 29 U.S.C. § 207"),
    ("Colômbia", "eco-6x1", 0, "A Lei 2.101/2021 reduziu a jornada máxima para 42 horas semanais, em 5 ou 6 dias.",
     "http://www.secretariasenado.gov.co/senado/basedoc/ley_2101_2021.html",
     "la duración máxima de la jornada ordinaria de trabajo es de cuarenta y dos (42) horas a la semana, que podrán ser distribuidas, de común acuerdo, entre empleador y trabajador, en 5 o 6 días a la semana", "Secretaria do Senado, Lei 2.101/2021"),
    ("Argentina", "eco-6x1", -1, "A Lei 11.544 permite até 8 horas por dia e 48 horas por semana.",
     "https://servicios.infoleg.gob.ar/infolegInternet/anexos/60000-64999/63368/norma.htm",
     "la duración del trabajo no podrá exceder de ocho horas diarias o cuarenta y ocho horas semanales", "InfoLEG, Lei 11.544"),
    # seg-maioridade: "A maioridade penal deve cair para 16 anos nos crimes mais graves, como os hediondos."
    ("EUA", "seg-maioridade", 1, "A lei federal (18 U.S.C. § 5032) permite processar como adulto quem tem 15 anos ou mais e comete crime violento grave.",
     "https://www.law.cornell.edu/uscode/text/18/5032",
     "with respect to a juvenile fifteen years and older alleged to have committed an act after his fifteenth birthday which if committed by an adult would be a felony that is a crime of violence", "Cornell LII, 18 U.S.C. § 5032",
     ["proceeded against as an adult"]),
    ("Alemanha", "seg-maioridade", -1, "A Lei dos Tribunais de Menores (JGG, § 1) aplica a lei juvenil a quem tem de 14 anos até os 18 incompletos.",
     "https://www.gesetze-im-internet.de/jgg/__1.html", "jugendlicher ist, wer zur zeit der tat vierzehn, aber noch nicht achtzehn", "Gesetze im Internet, JGG § 1"),
    ("Espanha", "seg-maioridade", -1, "A Lei Orgânica 5/2000 (art. 1) aplica a lei de menores a quem tem mais de 14 e menos de 18 anos.",
     "https://www.boe.es/buscar/act.php?id=BOE-A-2000-641", "la responsabilidad de las personas mayores de catorce años y menores de dieciocho", "BOE, Lei Orgânica 5/2000"),
    ("Portugal", "seg-maioridade", 1, "O Código Penal (art. 19) só considera inimputáveis os menores de 16 anos; a partir dos 16 responde-se pelo Código Penal.",
     "https://www.pgdlisboa.pt/leis/lei_mostra_articulado.php?artigo_id=109A0019&nid=109&tabela=leis&pagina=1&ficha=1&so_miolo=&nversao=",
     "os menores de 16 anos são inimputáveis", "PGD Lisboa, Código Penal, art. 19"),
    ("Argentina", "seg-maioridade", 1, "A Lei 22.278 (art. 1) não pune menores de 16 anos; dos 16 aos 18 a punição vale para crimes com pena de prisão acima de 2 anos.",
     "https://servicios.infoleg.gob.ar/infolegInternet/anexos/110000-114999/114167/texact.htm",
     "no es punible el menor que no haya cumplido dieciséis (16) años de edad", "InfoLEG, Lei 22.278",
     ["tampoco lo es el que no haya cumplido dieciocho (18) años, respecto de delitos de acción privada o reprimidos con pena privativa de la libertad que no exceda de dos (2) años"]),
    ("Uruguai", "seg-maioridade", -1, "O Código da Infância e Adolescência (Lei 17.823) trata como adolescente quem tem de 13 a 18 anos, com regime próprio para infrações penais.",
     "https://www.impo.com.uy/bases/codigo-ninez-adolescencia/17823-2004",
     "por adolescente a los mayores de trece y menores de dieciocho años de edad", "IMPO, Lei 17.823",
     ["de los adolescentes y las infracciones a la ley penal"]),
    ("Chile", "seg-maioridade", -1, "A Lei 20.084 aplica a responsabilidade penal adolescente a quem tem mais de 14 e menos de 18 anos.",
     "https://nuevo.leychile.cl/servicios/Navegar/get_norma_json?idNorma=244803",
     "sean mayores de catorce y menores de dieciocho años, los que, para los efectos de esta ley, se consideran adolescentes", "BCN LeyChile, Lei 20.084"),
    ("México", "seg-maioridade", -1, "A Lei Nacional do Sistema de Justiça Penal para Adolescentes aplica regime próprio a quem tem de 12 a 18 anos incompletos.",
     "https://web.archive.org/web/2025id_/https://www.diputados.gob.mx/LeyesBiblio/pdf/LNSIJPA.pdf",
     "tengan entre doce años cumplidos y menos de dieciocho años de edad", "Câmara dos Deputados do México, LNSIJPA (cópia do Internet Archive)"),
    ("Rússia", "seg-maioridade", 1, "O Código Penal (art. 20) fixa a responsabilidade penal aos 16 anos, e aos 14 para crimes graves listados.",
     "https://www.consultant.ru/document/cons_doc_LAW_10699/fd969cc22a68d513db2c83a94d6ad355a95dbec7/",
     "уголовной ответственности подлежит лицо, достигшее ко времени совершения преступления шестнадцатилетнего возраста", "ConsultantPlus, Código Penal, art. 20",
     ["лица, достигшие ко времени совершения преступления четырнадцатилетнего возраста, подлежат уголовной ответственности"]),
    ("China", "seg-maioridade", 1, "A Lei Penal (art. 17) faz responder criminalmente quem tem 16 anos, e a partir dos 14 por crimes graves como homicídio e estupro.",
     "http://www.npc.gov.cn/zgrdw/englishnpc/Law/2007-12/13/content_1384075.htm",
     "if a person who has reached the age of 16 commits a crime, he shall bear criminal responsibility", "Assembleia Popular Nacional, Lei Penal (tradução oficial)",
     ["if a person who has reached the age of 14 but not the age of 16 commits intentional homicide"]),
    ("Índia", "seg-maioridade", 1, "A Lei de Justiça Juvenil de 2015 (seções 15 e 18) permite julgar como adulto quem tem 16 anos ou mais e comete crime hediondo.",
     "https://web.archive.org/web/2023id_/https://www.indiacode.nic.in/bitstream/123456789/2148/1/A2016-2.pdf",
     "pass an order that there is a need for trial of the said child as an adult", "India Code, Juvenile Justice Act 2015 (cópia do Internet Archive)",
     ["in case of a heinous offence alleged to have been committed by a child, who has completed or is above the age of sixteen years"]),
    ("Canadá", "seg-maioridade", 0, "Jovens são julgados na justiça juvenil, mas quem tem 14 anos ou mais pode receber pena de adulto por crime com pena acima de 2 anos (YCJA, s. 64).",
     "https://laws-lois.justice.gc.ca/eng/acts/y-1.5/page-8.html",
     "found guilty of an offence for which an adult is liable to imprisonment for a term of more than two years and that was committed after the young person attained the age of 14 years", "Justice Laws, Youth Criminal Justice Act"),

    # seg-armas: "O acesso de civis a armas de fogo deve ser ampliado."
    ("EUA", "seg-armas", 1, "A Segunda Emenda da Constituição garante o direito do povo de ter e portar armas.",
     f"{C}/United_States_of_America_1992?lang=en", "the right of the people to keep and bear arms, shall not be infringed", f"{CRT}, EUA"),
    ("Reino Unido", "seg-armas", -1, "Ter arma de fogo exige certificado policial, dado só a quem prova ter boa razão para ela (Firearms Act 1968, seções 1 e 27).",
     "https://web.archive.org/web/2025id_/https://www.legislation.gov.uk/ukpga/1968/27/section/27",
     "that he has a good reason for having in his possession, or for purchasing or acquiring, the firearm", "legislation.gov.uk, Firearms Act 1968 (cópia do Internet Archive)",
     [("https://web.archive.org/web/2025id_/https://www.legislation.gov.uk/ukpga/1968/27/section/1", "without holding a firearm certificate in force at the time")]),
    ("Alemanha", "seg-armas", -1, "A Lei de Armas (WaffG, § 8) exige comprovar necessidade, como caça ou tiro esportivo, para ter arma.",
     "https://www.gesetze-im-internet.de/waffg_2002/__8.html", "der nachweis eines bedürfnisses ist erbracht, wenn", "Gesetze im Internet, WaffG § 8",
     ["vor allem als jäger, sportschütze"]),
    ("Índia", "seg-armas", -1, "A Lei de Armas de 1959 exige licença para ter arma, dada só a quem tem boa razão (seções 3 e 13).",
     "https://web.archive.org/web/2025id_/https://www.indiacode.nic.in/bitstream/123456789/1398/1/A1959-54.pdf",
     "no person shall acquire, have in his possession, or carry any firearm or ammunition unless he holds in this behalf a licence", "India Code, Arms Act 1959 (cópia do Internet Archive)",
     ["the person by whom the licence is required has a good reason for obtaining the same"]),

    # eco-reforma-tributaria: has a VAT-type consumption tax (the reform replaces several consumption taxes by a dual VAT).
    ("Espanha", "eco-reforma-tributaria", 1, "A Espanha cobra o IVA, imposto sobre valor agregado (Lei 37/1992).",
     "https://www.boe.es/buscar/act.php?id=BOE-A-1992-28740", "el impuesto sobre el valor añadido es un tributo de naturaleza indirecta que recae sobre el consumo", "BOE, Lei 37/1992"),
    ("Alemanha", "eco-reforma-tributaria", 1, "A Alemanha cobra a Umsatzsteuer, seu imposto sobre valor agregado (UStG, § 1).",
     "https://www.gesetze-im-internet.de/ustg_1980/__1.html", "der umsatzsteuer unterliegen die folgenden umsätze", "Gesetze im Internet, UStG § 1"),
    ("Suécia", "eco-reforma-tributaria", 1, "A Suécia cobra imposto sobre valor agregado (mervärdesskatt), regido pela Lei 2023:200.",
     "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/mervardesskattelag-2023200_sfs-2023-200/",
     "mervärdesskattelag (2023:200)", "Riksdagen, Mervärdesskattelag (2023:200)"),
    ("Argentina", "eco-reforma-tributaria", 1, "A Argentina cobra o IVA (Lei 23.349, texto ordenado de 1997).",
     "https://servicios.infoleg.gob.ar/infolegInternet/anexos/40000-44999/42701/texact.htm",
     "ley de impuesto al valor agregado, sustituido por el artículo 1° de la ley n° 23.349", "InfoLEG, Lei do IVA"),
    ("Chile", "eco-reforma-tributaria", 1, "O Chile cobra o IVA sobre vendas e serviços (Decreto-Lei 825).",
     "https://nuevo.leychile.cl/servicios/Navegar/get_norma_json?idNorma=6369",
     "el impuesto de este título afecta a las ventas y servicios", "BCN LeyChile, Decreto-Lei 825",
     ["impuesto al valor agregado"]),
    ("México", "eco-reforma-tributaria", 1, "O México cobra o IVA, criado pela lei de 1978.",
     "https://web.archive.org/web/2025id_/https://www.diputados.gob.mx/LeyesBiblio/pdf/LIVA.pdf",
     "están obligadas al pago del impuesto al valor agregado establecido en esta ley", "Câmara dos Deputados do México, Lei do IVA (cópia do Internet Archive)",
     ["publicada en el diario oficial de la federación el 29 de diciembre de 1978"]),
    ("Japão", "eco-reforma-tributaria", 1, "O Japão cobra o imposto sobre consumo, com crédito do imposto pago nas compras, como um IVA.",
     "https://www.nta.go.jp/english/taxes/consumption_tax/01.htm", "consumption tax is levied on", "Agência Nacional de Tributos do Japão",
     ["taxable purchase that is eligible for tax credit"]),
    ("Canadá", "eco-reforma-tributaria", 1, "O Canadá cobra o GST, imposto sobre bens e serviços com crédito do imposto pago nos insumos (Excise Tax Act, parte IX).",
     "https://laws-lois.justice.gc.ca/eng/acts/e-15/page-24.html", "part ix - goods and services tax", "Justice Laws, Excise Tax Act",
     ["input tax credits"]),
    ("EUA", "eco-reforma-tributaria", -1, "Os EUA são o único país da OCDE sem imposto sobre valor agregado (relatório CRS R41708 do Congresso).",
     "https://www.everycrsreport.com/reports/R41708.html", "the united states is the only member without a vat", "Congressional Research Service, R41708"),

    # eco-privatizacao: "Empresas estatais como a Eletrobras devem ser privatizadas."
    ("Suécia", "eco-privatizacao", -1, "A Vattenfall, maior empresa de energia do país, pertence 100% ao Estado sueco.",
     "https://group.vattenfall.com/who-we-are", "vattenfall ab is 100% owned by the swedish state", "Vattenfall, página institucional"),
    ("EUA", "eco-privatizacao", 1, "Empresas privadas de capital aberto atendiam 72% dos consumidores de energia em 2017 (EIA).",
     "https://www.eia.gov/todayinenergy/detail.php?id=40913", "investor-owned utilities served 72% of u.s. electricity customers in 2017", "U.S. Energy Information Administration"),

    # amb-margem-equatorial: is new offshore oil exploration licensed?
    ("Espanha", "amb-margem-equatorial", -1, "A Lei 7/2021 de mudança climática (art. 9) proíbe novas licenças de exploração de petróleo e gás, inclusive no mar.",
     "https://www.boe.es/buscar/act.php?id=BOE-A-2021-8447",
     "no se otorgarán en el territorio nacional, incluido el mar territorial, la zona económica exclusiva y la plataforma continental, nuevas autorizaciones de exploración", "BOE, Lei 7/2021"),
    ("EUA", "amb-margem-equatorial", 1, "O governo aprova a cada 5 anos um calendário de leilões de áreas de petróleo e gás no mar (OCS Lands Act, seção 18).",
     "https://www.boem.gov/oil-gas-energy/national-program",
     "the secretary of the interior is responsible for approving a schedule of ocs oil and gas lease sales for a 5-year period", "BOEM, National OCS Program"),

    # soc-cotas: race- or caste-based university admission.
    ("EUA", "soc-cotas", -1, "A Suprema Corte (SFFA v. Harvard, 2023) derrubou o uso da raça na admissão de Harvard e da Universidade da Carolina do Norte.",
     "https://www.supremecourt.gov/opinions/22pdf/20-1199_hgdj.pdf",
     "both programs lack sufficiently focused and measurable objectives warranting the use of race", "Suprema Corte dos EUA, SFFA v. Harvard (2023)"),
    ("Índia", "soc-cotas", 1, "A Constituição (art. 15) permite reservar vagas no ensino para castas e tribos registradas e classes atrasadas.",
     f"{C}/India_2023?lang=en", "or for the scheduled castes or the scheduled tribes in so far as such special provisions relate to their admission to educational institutions", f"{CRT}, Índia"),
    ("Rússia", "eco-reforma-tributaria", 1, "A Rússia cobra o imposto sobre valor agregado (NDS), regido pelo Código Tributário (art. 143).",
     "https://www.consultant.ru/document/cons_doc_LAW_28165/2ade1f82a7dbf4c31bcce5c8df14ca42d9fd66b7/",
     "налогоплательщиками налога на добавленную стоимость", "ConsultantPlus, Código Tributário, art. 143"),
    ("Colômbia", "eco-reforma-tributaria", 1, "A Colômbia cobra o IVA (imposto sobre as vendas, com desconto do imposto pago antes), regido pelo Estatuto Tributário.",
     "http://www.secretariasenado.gov.co/senado/basedoc/estatuto_tributario_pr017.html",
     "la tarifa general del impuesto sobre las ventas prevista en este estatuto", "Secretaria do Senado, Estatuto Tributário",
     ["impuestos descontables"]),
    ("Rússia", "seg-drogas", 0, "Guardar droga sem intenção de vender é infração administrativa, com multa ou detenção de até 15 dias (Código de Infrações, art. 6.8); em quantidade significativa vira crime (Código Penal, art. 228).",
     "https://www.consultant.ru/document/cons_doc_LAW_34661/8c58af8ec7516f0ddf1334e950f3a60ea525ca28/",
     "незаконные приобретение, хранение, перевозка, изготовление, переработка без цели сбыта наркотических средств", "ConsultantPlus, Código de Infrações Administrativas, art. 6.8",
     ["административный арест на срок до пятнадцати суток",
      ("https://www.consultant.ru/document/cons_doc_LAW_10699/a109722731a0509e104278d1b2d2f589beee330f/", "без цели сбыта наркотических средств , психотропных веществ или их аналогов в значительном размере")]),
]
