"""Explainers for the Paraíba questions. Arguments come from people outside the 2026 PB ballot."""

SOURCES = {
    "ppp-lei": ("https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2004/lei/l11079.htm", "Lei 11.079/2004 (Lei das PPPs), Planalto"),
    "estatais": ("https://www12.senado.leg.br/noticias/infomaterias/2023/02/privatizacao-desmonte-do-estado-ou-modernizacao-de-empresas-ineficientes",
                 "Agência Senado, especial de 02/2023"),
    "san-aprova": ("https://www12.senado.leg.br/noticias/materias/2020/06/24/senado-aprova-novo-marco-legal-do-saneamento-basico",
                   "Agência Senado, 24/06/2020"),
    "san-debate": ("https://www12.senado.leg.br/noticias/materias/2020/06/24/para-a-maioria-dos-senadores-o-novo-marco-legal-vai-melhorar-o-saneamento-basico-no-pais",
                   "Agência Senado, 24/06/2020"),
    "cagepa": ("https://movimentoeconomico.com.br/saneamento/2026/05/15/acciona-vence-ppp-da-cagepa-com-r-3-bilhoes-e-unico-lance-na-b3/",
               "Movimento Econômico, 15/05/2026"),
    "icms-cons": ("https://www12.senado.leg.br/noticias/materias/2013/03/11/isencoes-do-icms-na-guerra-fiscal-afetam-a-produtividade-da-economia-no-longo-prazo-diz-consultor",
                  "Agência Senado, 11/03/2013"),
    "icms-2032": ("https://www12.senado.leg.br/noticias/materias/2021/10/06/aprovado-projeto-que-prorroga-incentivos-fiscais-a-empresas-por-ate-15-anos",
                  "Agência Senado, 06/10/2021"),
    "rt-senado": ("https://www12.senado.leg.br/noticias/materias/2023/11/08/senado-aprova-reforma-tributaria-no-primeiro-turno-no-plenario",
                  "Agência Senado, 08/11/2023"),
    "fain-lei": ("https://sapl.al.pb.leg.br/media/sapl/public/materialegislativa/2015/49332/49332_texto_integral.pdf",
                 "ALPB, Projeto de Lei 639/2015 do Poder Executivo"),
    "cf": ("https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm", "Constituição Federal, Planalto"),
    "pm-pec": ("https://www12.senado.leg.br/institucional/datasenado/materias/enquetes/desmilitarizacao-da-pm", "DataSenado, enquete sobre a PEC 51/2013"),
    "pm-lind": ("https://www12.senado.leg.br/noticias/materias/2014/03/20/lindberg-farias-defende-proposta-de-reformulacao-da-policia",
                "Agência Senado, 20/03/2014"),
    "pm-cam": ("https://www.camara.leg.br/noticias/486465-desmilitarizacao-da-policia-divide-opinioes-em-audiencia-publica-na-camara/",
               "Agência Câmara, audiência pública"),
    "cac-pauta": ("https://sapl.al.pb.leg.br/media/sapl/public/sessaoplenaria/1187/pauta/1187_pauta_sessao.pdf", "ALPB, pauta da sessão de 14/02/2023"),
    "arm-ccj": ("https://www12.senado.leg.br/noticias/materias/2023/04/19/senadores-e-especialistas-divergem-sobre-regras-para-uso-de-armas",
                "Agência Senado, 19/04/2023"),
    "arm-pdl": ("https://www12.senado.leg.br/noticias/materias/2026/02/20/csp-vota-projetos-para-derrubar-decreto-que-restringiu-acesso-a-armas",
                "Agência Senado, 20/02/2026"),
    "ns-pauta": ("https://sapl.al.pb.leg.br/media/sapl/public/sessaoplenaria/1350/pauta/ordem_do_dia_23.09.2025_3a_sessao_ordinaria_itinerante.pdf",
                 "ALPB, ordem do dia de 23/09/2025"),
    "ns-decreto": ("https://agenciabrasil.ebc.com.br/direitos-humanos/noticia/2016-04/publicado-decreto-que-autoriza-nome-social-de-travestis-no-servico",
                   "Agência Brasil, 29/04/2016"),
    "ns-senado": ("https://www12.senado.leg.br/institucional/responsabilidade-social/equidade/equidade-eventos/retificacao-do-registro-e-nome-social-sao-conquistas-da-comunidade-trans",
                  "Senado Federal, Equidade"),
    "ns-ovando": ("https://www.camara.leg.br/noticias/1143419-projeto-suspende-uso-de-nome-social-em-concurso/", "Agência Câmara, 2025"),
    "vs-guedes": ("https://agenciabrasil.ebc.com.br/saude/noticia/2020-10/jamais-esteve-sob-analise-privatizar-o-sus-diz-guedes",
                  "Agência Brasil, 29/10/2020"),
    "vs-sus": ("https://www12.senado.leg.br/noticias/materias/2018/08/13/incentivo-fiscal-e-politica-de-precos-de-planos-de-saude-agravam-a-situacao-dos-sus-dizem-debatedores",
               "Agência Senado, 13/08/2018"),
}

EXPLAINERS = {
    "pb-concessoes-ppp": {
        "whatItIs": [
            ("Concessão é um contrato em que uma empresa privada constrói ou opera um serviço público por vários anos. Na PPP (parceria público-privada), além da tarifa paga pelos usuários, o governo também paga a empresa.",
             "Concessão patrocinada é a concessão de serviços públicos ou de obras públicas de que trata a Lei nº 8.987, de 13 de fevereiro de 1995, quando envolver, adicionalmente à tarifa cobrada dos usuários contraprestação pecuniária do parceiro público ao parceiro privado.", "ppp-lei"),
            ("Em 15/05/2026 o grupo espanhol Acciona venceu o leilão da PPP de esgoto da Cagepa, a companhia de água e esgoto do governo da Paraíba.",
             "O grupo espanhol Acciona venceu nesta sexta-feira (15) o leilão da Parceria Público-Privada (PPP) de esgotamento sanitário da Companhia de Água e Esgotos da Paraíba ( Cagepa )", "cagepa"),
        ],
        "inPractice": [
            ("O contrato da Cagepa dura 25 anos e prevê R$ 3 bilhões em obras de esgoto.",
             "O contrato, com prazo de 25 anos, prevê R$ 3 bilhões em investimentos.", "cagepa"),
            ("A água continua com a Cagepa, que também fiscaliza a empresa. A empresa privada cuida da coleta e do tratamento de esgoto.",
             "O abastecimento de água segue integralmente sob responsabilidade da Cagepa , que também permanecerá responsável pela gestão e fiscalização da parceria.", "cagepa"),
            ("Hoje o esgoto chega a 6,71% das casas urbanas no Alto Piranhas e a 46,43% no Litoral.",
             "Os índices atuais de atendimento de esgoto urbano nas microrregiões são de 6,71% no Alto Piranhas e 46,43% no Litoral .", "cagepa"),
        ],
        "argsFor": [
            ("O economista Armando Castelar (FGV) argumenta que o governo não tem dinheiro para tantas obras e que, nos contratos com empresas, o serviço não pode parar.",
             "Nos contratos com a iniciativa privada, os serviços não podem parar.", "estatais"),
            ("O presidente da Cagepa, Marcus Vinícius, disse que a parceria dá à companhia sustentabilidade financeira e mais capacidade de investir.",
             "Essa parceria representa uma virada de chave para a Cagepa e para o estado, garantindo sustentabilidade financeira, fortalecimento da governança", "cagepa"),
        ],
        "argsAgainst": [
            ("No debate do marco do saneamento, o senador Weverton disse que o investimento privado tende a ficar nas grandes cidades e não chegar às pequenas do Norte e do Nordeste.",
             "Sabemos que, infelizmente quanto às cidades pequenas, principalmente do Norte e do Nordeste, esses investimentos não vão chegar, como foi aqui falado.", "san-debate"),
            ("O senador Rogério Carvalho avaliou que abrir o setor a empresas privadas pode desvalorizar as empresas públicas de saneamento.",
             "Em sua avaliação, as mudanças previstas pelo projeto poderão gerar desvalorização das empresas públicas de saneamento, o que pode prejudicar o patrimônio dessas estatais.", "san-debate"),
        ],
        "nuance": [
            ("Concessão não é venda da empresa: a Cagepa continua do governo. O que passa à empresa privada é a obra e a operação do esgoto, por prazo definido.",
             "Privatização, hoje em dia, não é apenas vender os ativos de uma empresa estatal, mas também trazer o investidor privado para fazer coisas que o setor público antes fazia, seja por meio de parcerias público-privadas, seja por meio de concessões.", "estatais"),
            ("No leilão da Cagepa só uma empresa deu lance, com desconto de 1% sobre o valor máximo que o estado aceitava pagar.",
             "A empresa foi a única a apresentar proposta no certame paraibano e ofereceu deságio de 1% sobre a contraprestação pública máxima fixada em edital.", "cagepa"),
        ],
    },
    "pb-incentivos-fiscais": {
        "whatItIs": [
            ("Incentivo fiscal é quando o estado cobra menos ICMS, o imposto estadual sobre mercadorias, de uma empresa para atraí-la ao estado.",
             "mediante concessões de isenções fiscais para atrair o investimento produtivo das empresas", "icms-cons"),
            ("Na Paraíba, esse desconto vem do FAIN (Fundo de Apoio ao Desenvolvimento Industrial da Paraíba): um conselho do governo aprova, por resolução, o benefício de cada indústria.",
             "Condiciona a fruição do benefício previsto em Resolução do Conselho Deliberativo do Fundo de Apoio ao Desenvolvimento Industrial da Paraíba - FAIN", "fain-lei"),
            ("Quando vários estados fazem isso ao mesmo tempo, disputando empresas, chama-se guerra fiscal.",
             "A guerra fiscal é resultado da concessão unilateral de isenções e benefícios fiscais do ICMS por parte de estados que buscam atrair investimentos para seus territórios.", "icms-2032"),
        ],
        "inPractice": [
            ("Uma lei de 2021 permitiu prorrogar esses benefícios até 2032.",
             "que prorroga até 2032 incentivos fiscais concedidos pelos estados e pelo Distrito Federal para empresas no âmbito da guerra fiscal", "icms-2032"),
            ("A reforma tributária muda a cobrança para o estado onde o produto é consumido, o que reduz a força desses incentivos a partir da transição.",
             "A mudança visa dar fim à chamada guerra fiscal — a concessão de benefícios tributários por estados com o objetivo de atrair investimentos.", "rt-senado"),
        ],
        "argsFor": [
            ("A senadora Rose de Freitas, relatora da prorrogação, argumentou que o incentivo não é perda de receita, porque sem ele a empresa nem viria para o estado.",
             "A concessão de incentivos fiscais não constitui renúncia de receitas (fiscal), visto que os Estados nunca tiveram a receita correspondente", "icms-2032"),
            ("Segundo o consultor do Senado Márcio de Oliveira Júnior, para estados menos desenvolvidos o incentivo gera emprego e renda locais.",
             "por um lado, produz benefícios locais em termos de geração de emprego e renda", "icms-cons"),
        ],
        "argsAgainst": [
            ("O mesmo consultor, Márcio de Oliveira Júnior, diz que o uso generalizado prejudica a produtividade do país e que a maior beneficiada é a empresa.",
             "gera efeitos deletérios sobre a produtividade da economia no longo prazo, inclusive por conta da incerteza jurídica advinda de benefícios fiscais concedidos ao arrepio da lei", "icms-cons"),
            ("O senador José Aníbal chamou a guerra fiscal de \"uma corrida para o fundo\".",
             "São Paulo está sempre na mira dos subsídios e da guerra fiscal, que é uma corrida para o fundo, não é para a frente e nem para o alto.", "icms-2032"),
        ],
        "nuance": [
            ("A pergunta inclui uma condição: manter o incentivo cobrando metas de investimento e emprego. Segundo o consultor, o ganho do estado vem justamente dos empregos criados pela empresa que se instala.",
             "Já o estado concedente da isenção, teria algum ganho na criação de novos postos de trabalho decorrentes da instalação da nova empresa", "icms-cons"),
            ("Para o consultor, o ganho para a população do próprio estado tende a ser menor que o da empresa beneficiada.",
             "mas para o país como um todo — e mesmo para o conjunto da população do estado — o benefício seria consideravelmente menor", "icms-cons"),
        ],
    },
    "pb-cac-arma": {
        "whatItIs": [
            ("CAC é a sigla para caçadores, atiradores desportivos e colecionadores de armas, que têm registro próprio.",
             "restringiu a atividade dos caçadores, atiradores e colecionadores (CACs).", "arm-pdl"),
            ("Um projeto aprovado na Assembleia da Paraíba \"reconhece o risco da atividade\" e a necessidade de arma para atiradores esportivos. O governador vetou o projeto por inconstitucionalidade.",
             "Reconhece o risco da atividade e a efetiva necessidade do aporte de arma de fogo aos atiradores desportivos integrantes de entidades legalmente constituídas no âmbito do Estado da Paraíba", "cac-pauta"),
        ],
        "inPractice": [
            ("Regras de armas são federais: o Estatuto do Desarmamento é uma lei nacional regulamentada por decreto do presidente. Por isso o veto alegou inconstitucionalidade.",
             "RAZÕES DO VETO: INCONSTITUCIONALIDADE", "cac-pauta"),
            ("O número de CACs saltou de cerca de 60 mil em 2017 para mais de 800 mil em 2022, segundo o pesquisador Roberto Uchôa.",
             "Nós tínhamos, em 2017, cerca de 60 mil CACs registrados em todo o Brasil. A gente fecha 2022 com mais de 800 mil CACs registrados.", "arm-ccj"),
        ],
        "argsFor": [
            ("O senador Magno Malta argumentou que tirar o registro exige escola de tiro, testes psicológicos e antecedentes criminais.",
             "Você vai para uma escola [de tiro], você tem que se inscrever, tem seus documentos, tem psicólogos, tem psiquiatras, você faz teste psicológico, traz antecedentes criminais", "arm-ccj"),
            ("O senador Marcio Bittar disse que as restrições federais limitam o tiro desportivo e trazem perdas ao setor.",
             "Ele afirma que o Decreto 11.615 contém “vícios” que, entre outros aspectos, limitam a prática do tiro desportivo", "arm-pdl"),
        ],
        "argsAgainst": [
            ("O pesquisador Roberto Uchôa disse que muitos se tornaram CAC para circular armados sem conseguir porte na Polícia Federal.",
             "Eram pessoas que não estavam conseguindo o porte de arma pela Polícia Federal, seja porque não tinham razões para tal, seja porque não conseguiam justificar essa necessidade", "arm-ccj"),
            ("Carolina Taboada, do Instituto Igarapé, apontou que só 2,3% dos acervos de CACs e clubes foram fiscalizados em 2020.",
             "em 2020, somente 2,3% dos arcervos de CACs, clubes e entidades de tiros foram fiscalizados", "arm-ccj"),
        ],
        "nuance": [
            ("Na Assembleia, votar SIM num veto derruba o veto e aprova o projeto; votar NÃO mantém o veto. Por isso o voto de cada deputado num veto também reflete sua relação com o governo estadual.",
             "VOTANDO SIM O DEPUTADO REJEITA O VETO, APROVANDO O PROJETO, E VOTANDO NÃO, ACEITA O VETO, REJEITANDO O PROJETO", "cac-pauta"),
            ("Mesmo entre críticos da flexibilização, há quem aceite o tiro esportivo e mire só o uso do registro de CAC como atalho para o porte.",
             "e viam na possibilidade de se tornar CAC uma forma de circularem armados.", "arm-ccj"),
        ],
    },
    "pb-nome-social": {
        "whatItIs": [
            ("Nome social é o nome pelo qual uma pessoa travesti ou transexual se identifica e é reconhecida, diferente do nome no registro civil.",
             "o nome social configura a designação pela qual a pessoa se identifica e é socialmente reconhecida", "ns-decreto"),
            ("Desde 2016 um decreto obriga órgãos federais a usar o nome social quando a pessoa pede.",
             "deverão adotar o nome social da pessoa travesti ou transexual, de acordo com seu requerimento e com o disposto neste decreto", "ns-decreto"),
        ],
        "inPractice": [
            ("O projeto da Assembleia da Paraíba permitiria incluir o nome social nas contas e comunicações das concessionárias de água, luz e gás. O governador vetou o projeto.",
             "Dispõe sobre a possibilidade de inclusão do nome social dos consumidores nas comunicações realizadas pelas concessionárias estaduais de água, luz e gás encanado", "ns-pauta"),
            ("Desde 2018 é possível mudar nome e gênero direto no cartório, sem processo judicial, mas muita gente ainda não fez a retificação.",
             "publicou um normativo ( Provimento 73/2018 ) que passou a exigir que todos os cartórios de registro de pessoas do país realizassem a mudança, sem a necessidade de processo judicial.", "ns-senado"),
        ],
        "argsFor": [
            ("A Antra (Associação Nacional de Travestis e Transexuais) estima que ao menos 63,6% das pessoas trans ainda não conseguiram retificar os documentos, por custo e falta de informação.",
             "dados da Associação Nacional de Travestis e Transexuais (Antra) informam que pelos menos 63,6% dessas pessoas ainda não conseguiram a retificação", "ns-senado"),
            ("Lui Oliveira, servidor do Senado, contou que evitou usar o nome social por medo de discriminação até se sentir seguro.",
             "Enquanto estagiário, eu tive a possibilidade de já preencher o nome social no ato do cadastro, mas não o fiz pelo receio da discriminação.", "ns-senado"),
        ],
        "argsAgainst": [
            ("O deputado Dr. Luiz Ovando (PP-MS) argumentou que regras de nome social podem gerar tratamentos diferenciados e ferir a igualdade (isonomia).",
             "Dr. Luiz Ovando argumenta que a norma pode gerar desigualdades e ferir o princípio da isonomia.", "ns-ovando"),
            ("Luiz Ovando também disse que esse tipo de norma pode transformar a administração pública em \"espaço de militância política\".",
             "pode transformar a administração pública em um espaço de militância política, em vez de um local onde prevaleça a competência técnica e o mérito.", "ns-ovando"),
        ],
        "nuance": [
            ("O veto estadual citou inconstitucionalidade e interesse público, não só o mérito: parte da discussão é se o estado pode impor isso a concessionárias.",
             "RAZÕES DO VETO: INCONSTITUCIONALIDADE E CONTRÁRIO AO INTERESSE PÚBLICO", "ns-pauta"),
            ("Usar o nome social é opcional e não muda o registro civil: o nome do registro continua existindo para fins administrativos.",
             "Nesse caso, o nome do registro civil deve permanecer confidencial e ser utilizado somente com autorização da pessoa ou para fins estritamente necessários.", "ns-senado"),
        ],
    },
}

TOPICS = {
    "pb-concessoes-ppp": ["concess", "parceria", "PPP", "privatiza", "saneamento", "Cagepa", "esgoto"],
    "pb-incentivos-fiscais": ["incentivo", "isenç", "guerra fiscal", "ICMS", "FAIN", "benefício"],
    "pb-cac-arma": ["arma", "atirador", "CAC"],
    "pb-nome-social": ["nome social"],
}
