"""Explainers for the security and justice questions."""

SOURCES = {
    "sai-senado": ("https://www12.senado.leg.br/noticias/materias/2024/02/20/senado-aprova-restricao-as-saidinhas-de-presos-texto-volta-para-a-camara",
                   "Agência Senado, 20/02/2024"),
    "sai-debate": ("https://www12.senado.leg.br/noticias/materias/2024/02/23/debate-sobre-fim-dos-saidoes-expoe-desafios-da-ressocializacao",
                   "Agência Senado, 23/02/2024"),
    "sai-veto": ("https://www12.senado.leg.br/noticias/materias/2024/05/28/pela-segunda-vez-congresso-acaba-com-saidas-temporarias-de-presos-em-feriados",
                 "Agência Senado, 28/05/2024"),
    "dro-senado": ("https://www12.senado.leg.br/noticias/materias/2024/04/16/senado-aprova-pec-sobre-drogas-que-segue-para-a-camara",
                   "Agência Senado, 16/04/2024"),
    "dro-stf": ("https://www12.senado.leg.br/radio/1/noticia/2025/02/18/stf-mantem-descriminalizacao-do-porte-de-maconha-mas-senado-tem-proposta-contraria-1",
                "Rádio Senado, 18/02/2025"),
    "jan-aprova": ("https://www12.senado.leg.br/noticias/materias/2025/12/17/pl-da-dosimetria-segue-para-sancao",
                   "Agência Senado, 17/12/2025"),
    "jan-debate": ("https://www12.senado.leg.br/noticias/materias/2025/12/17/senadores-divergem-sobre-pl-da-dosimetria",
                   "Agência Senado, 17/12/2025"),
    "jan-lei": ("https://www12.senado.leg.br/noticias/materias/2026/05/08/promulgada-lei-que-possibilita-reducao-de-penas-pelo-8-de-janeiro",
                "Agência Senado, 08/05/2026"),
    "bli-camara": ("https://www.camara.leg.br/noticias/1200769-camara-aprova-em-2-turno-o-texto-base-da-pec-das-prerrogativas",
                   "Agência Câmara, 17/09/2025"),
    "bli-ccj": ("https://www12.senado.leg.br/noticias/materias/2025/09/24/ccj-rejeita-pec-que-exige-autorizacao-para-acao-penal-contra-parlamentares",
                "Agência Senado, 24/09/2025"),
    "arm-ccj": ("https://www12.senado.leg.br/noticias/materias/2023/04/19/senadores-e-especialistas-divergem-sobre-regras-para-uso-de-armas",
                "Agência Senado, 19/04/2023"),
    "arm-pdl": ("https://www12.senado.leg.br/noticias/materias/2026/02/20/csp-vota-projetos-para-derrubar-decreto-que-restringiu-acesso-a-armas",
                "Agência Senado, 20/02/2026"),
    "mai-2015": ("https://www.camara.leg.br/noticias/467647-camara-aprova-em-2o-turno-reducao-da-maioridade-penal-em-crimes-graves/",
                 "Agência Câmara, 19/08/2015"),
    "mai-2026": ("https://www.camara.leg.br/noticias/1273975-ccj-adia-analise-de-propostas-que-reduzem-a-maioridade-penal-para-16-anos/",
                 "Agência Câmara, 2026"),
    "mai-senado": ("https://www12.senado.leg.br/radio/1/noticia/2026/02/02/morte-do-cao-orelha-reacende-debate-sobre-maioridade-penal",
                   "Rádio Senado, 02/02/2026"),
    "stf-pec": ("https://www12.senado.leg.br/noticias/materias/2023/02/14/pec-estipula-mandatos-de-oito-anos-para-ministros-do-stf",
                "Agência Senado, 14/02/2023"),
    "stf-plinio": ("https://www12.senado.leg.br/noticias/materias/2024/02/06/plinio-defende-fim-do-mandato-vitalicio-para-ministros-do-stf",
                   "Agência Senado, 06/02/2024"),
    "stf-ccj2009": ("https://www.migalhas.com.br/quentes/121500/ccj-do-senado-mantem-cargos-vitalicios-para-ministros-de-tribunais-superiores",
                    "Migalhas, CCJ do Senado, 2010"),
}

EXPLAINERS = {
    "seg-saidinha": {
        "whatItIs": [
            ("A saída temporária, a \"saidinha\", permitia que presos do regime semiaberto saíssem sem vigilância direta até cinco vezes por ano, em geral em feriados, para visitar a família ou estudar. Semiaberto é o regime em que o preso fica em colônia agrícola ou local parecido.",
             "Atualmente eles podem sair até cinco vezes ao ano, sem vigilância direta, para visitar a família, estudar fora da cadeia ou participar de atividades que contribuam para a ressocialização.", "sai-senado"),
            ("Para sair, o preso precisava ter bom comportamento e ter cumprido pelo menos 16,6% da pena, ou 25% se reincidente, com autorização do juiz.",
             "ter cumprido no mínimo 16,6% da pena, se for sua primeira condenação; ou 25%, se reincidente", "sai-debate"),
        ],
        "inPractice": [
            ("A saída em feriados já acabou: em maio de 2024 o Congresso derrubou o veto da Presidência da República e manteve só a saída para estudar.",
             "Com a derrubada do veto, volta a valer o sentido original do texto aprovado no Congresso: o benefício da saída temporária será concedido aos detentos em regime semiaberto apenas se for para cursar supletivo profissionalizante, ensino médio ou superior.", "sai-veto"),
            ("No 1º semestre de 2023, 11.415 presos não voltaram depois das saídas, segundo a Senappen, o equivalente a 6,27% dos presos do semiaberto.",
             "11.415 presos não retornaram depois das saídas temporárias do primeiro semestre de 2023. Isso representa 6,27% de todos presos que cumprem regime semiaberto no país", "sai-debate"),
        ],
        "argsFor": [
            ("O senador Sergio Moro (União-PR) argumentou que, somando quatro ou cinco feriados por ano, o número de presos que não voltam é grande e parte deles comete novos crimes.",
             "Se nós formos pensar em quatro ou cinco feriados por ano, 5% a cada uma dessas oportunidades, nós temos um número substancial de presos que não retornam.", "sai-debate"),
            ("O senador Fabiano Contarato (PT-ES), ex-delegado, votou pelo fim da saidinha e disse que o benefício passa \"a certeza da impunidade\".",
             "por entender que é mais um benefício dado e que vai passar não a sensação, mas a certeza da impunidade — disse.", "sai-senado"),
        ],
        "argsAgainst": [
            ("O autor do projeto original, deputado Pedro Paulo (PSD-RJ), citou dados de São Paulo: de 34 mil presos na saída de Natal de 2023, só 81 cometeram algum delito.",
             "Desses, 1,7 mil não retornaram no prazo. Muitos, depois, retornaram, mas só 81 cometeram algum tipo de delito, não necessariamente gravoso, ou seja: 0,23% — argumentou.", "sai-veto"),
            ("A deputada Érika Kokay (PT-DF) defendeu a saída para ver a família porque \"a família é agente fundamental de ressocialização\".",
             "Porque a família é agente fundamental de ressocialização.", "sai-veto"),
        ],
        "nuance": [
            ("Concordar com a frase hoje significa manter o fim da saidinha em feriados, que já está em lei. A saída para estudar continua permitida.",
             "o benefício da saída temporária será concedido aos detentos em regime semiaberto apenas se for para cursar supletivo profissionalizante, ensino médio ou superior.", "sai-veto"),
            ("Os mesmos números são lidos de formas opostas: o Conselho Nacional de Política Criminal chamou de \"ínfimo\" o número de presos que não voltam, e Moro discordou.",
             "“Trata-se de um quantitativo ínfimo se comparado ao número daqueles que cumpriram com as determinações legais e retornaram”, analisa o Conselho Nacional de Política Criminal e Penitenciária", "sai-debate"),
        ],
    },
    "seg-drogas": {
        "whatItIs": [
            ("A PEC 45/2023, aprovada no Senado em 2024 e enviada à Câmara, coloca na Constituição que é crime portar ou guardar droga ilícita em qualquer quantidade.",
             "A PEC 45/2023 insere no art. 5º da Constituição a determinação de que é crime a posse ou porte de qualquer quantidade de droga ou entorpecente", "dro-senado"),
            ("Ela foi uma reação ao STF, que decidiu que portar maconha para uso pessoal não é crime e fixou 40 gramas como referência para separar usuário de traficante.",
             "Foi estabelecido o parâmetro de 40g para diferenciar usuários de traficantes.", "dro-stf"),
        ],
        "inPractice": [
            ("Mesmo com a PEC, o usuário não iria preso: o texto prevê penas alternativas e tratamento. A Lei de Drogas de 2006 já não prevê prisão para quem porta para consumo.",
             "O texto aprovado nesta terça-feira não altera a Lei de Entorpecentes, que já prevê a diferenciação entre traficantes e usuários. Foi essa lei que extinguiu a pena de prisão para usuários no país.", "dro-senado"),
            ("Pela decisão do STF, portar maconha continua ilegal, e o uso em público segue proibido. A diferença é que a punição passa a ser administrativa, não criminal.",
             "O porte de maconha para consumo próprio segue sendo uma conduta ilegal, o que significa que o uso em espaços públicos continua proibido.", "dro-stf"),
        ],
        "argsFor": [
            ("O autor, senador Rodrigo Pacheco, argumentou que não existe tráfico sem comprador e que a decisão do STF invade a competência do Congresso e da Anvisa.",
             "O motivo desta dupla criminalização é que não há tráfico de drogas se não há interessado em adquiri-las.", "dro-senado"),
            ("O senador Alessandro Vieira afirmou que, nos países que liberaram, os indicadores mostram aumento da dependência e do consumo.",
             "porque todos os indicadores dos países que foram nesse sentido são de aumento da dependência, aumento do consumo", "dro-senado"),
        ],
        "argsAgainst": [
            ("O senador Jaques Wagner (PT-BA) disse que \"não será entupindo as cadeias\" que o problema das drogas será resolvido.",
             "Não será entupindo as cadeias que nós vamos resolver os problemas das drogas no Brasil — disse Jaques Wagner.", "dro-senado"),
            ("O senador Marcelo Castro (MDB-PI), psiquiatra, chamou a criminalização de retrocesso e disse que dependentes precisam de atendimento médico.",
             "Já o senador Marcelo Castro, MDB do Piauí, acredita que dependentes químicos precisam de atendimento médico e não ser tratados como criminosos. Para ele, a criminalização é um retrocesso.", "dro-stf"),
        ],
        "nuance": [
            ("Os dois lados concordam que traficante e usuário são diferentes. A disputa é se portar pouca quantidade deve ser crime ou infração administrativa, e quem decide isso: Congresso ou STF.",
             "Eles defenderam que é o Congresso Nacional que deve traçar políticas públicas sobre drogas, não o STF.", "dro-senado"),
            ("Discordar da frase não é o mesmo que defender a legalização da venda. A decisão do STF trata só do porte de maconha para uso pessoal.",
             "Os ministros do Supremo Tribunal Federal (STF) mantiveram o entendimento de que o porte de maconha para consumo pessoal não configura crime.", "dro-stf"),
        ],
    },
    "seg-8-janeiro": {
        "whatItIs": [
            ("Até abril de 2026, o STF havia condenado 1.402 pessoas pelos atos de 8 de janeiro de 2023; 431 receberam pena de prisão.",
             "at é abril de 2026 1.402 pessoas haviam sido condenadas pelos atos de 8 de janeiro. Desse total, 431 foram condenados a penas de prisão", "jan-lei"),
            ("A Lei da Dosimetria (Lei 15.402/2026) reduz essas penas. Foi vetada pela Presidência, e o Congresso derrubou o veto. Dosimetria é o cálculo do tamanho da pena.",
             "O veto foi derrubado em sessão do Congresso Nacional no dia 30 de abril.", "jan-lei"),
        ],
        "inPractice": [
            ("Quando vários crimes contra o Estado acontecem no mesmo contexto, o juiz passa a aplicar só a pena do mais grave, em vez de somar. Exemplo: 20 anos viram 12.",
             "Como exemplo, uma pessoa condenada às penas máximas pelos dois crimes teria uma pena total de 20 anos (8 anos pela abolição violenta do Estado democrático de direito, mais 12 anos pelo crime de golpe de Estado). Com a nova regra, a pena total será de 12 anos", "jan-lei"),
            ("Quem agiu \"em multidão\" sem financiar nem liderar ganha redução de um terço a dois terços. A revisão não é automática: cada defesa precisa pedir ao STF.",
             "A redução das penas não é automática. A definição dos novos tempos de condenação deve ocorrer quando a defesa de cada um dos condenados ingressar com o pedido", "jan-lei"),
        ],
        "argsFor": [
            ("O relator, senador Esperidião Amin, disse que \"a mão foi muito pesada\" nas condenações e que o projeto corrige distorções.",
             "Há um consenso de que a mão [nos julgamentos] foi muito pesada.", "jan-aprova"),
            ("A senadora Tereza Cristina reconheceu que houve crimes, mas disse que as penas impostas pelo STF são desproporcionais.",
             "Já a senadora Tereza Cristina (PP-MS) reconheceu que houve crimes no 8 de janeiro, mas afirmou que as penas impostas pelo STF são desproporcionais.", "jan-debate"),
        ],
        "argsAgainst": [
            ("O senador Renan Calheiros disse que os direitos dos condenados foram respeitados e que \"o que pacifica o país é golpista cumprir pena\".",
             "O que pacifica o país é golpista cumprir pena.", "jan-debate"),
            ("O senador Fabiano Contarato criticou a lei por ter \"endereço certo\": o ex-presidente Bolsonaro e seus auxiliares condenados.",
             "Estamos aqui legislando com endereço certo: o ex-presidente Bolsonaro e sua claque.", "jan-debate"),
        ],
        "nuance": [
            ("Há três posições, não duas: manter as penas, reduzi-las (o que virou lei) ou anistiar. Senadores como Marcos Rogério e Sergio Moro preferiam anistia e votaram na redução como \"ganho possível\".",
             "Ele registrou que preferia votar a anistia, mas admitiu que a redução de pena é o ganho possível para o momento.", "jan-debate"),
            ("A lei também alcança os condenados do chamado núcleo central, como o ex-presidente Jair Bolsonaro, condenado a 27 anos e 3 meses.",
             "figuram o ex-presidente Jair Bolsonaro (27 anos e 3 meses de prisão)", "jan-lei"),
        ],
    },
    "seg-blindagem": {
        "whatItIs": [
            ("A PEC 3/2021, chamada por defensores de \"PEC das Prerrogativas\" e por críticos de \"PEC da Blindagem\", exigiria autorização da Câmara ou do Senado para o STF abrir processo criminal contra um parlamentar.",
             "prevê autorização da Câmara ou do Senado para o Supremo Tribunal Federal (STF) processar deputado ou senador", "bli-camara"),
            ("A Câmara aprovou a PEC em setembro de 2025, e a CCJ do Senado a rejeitou por 26 votos a 0.",
             "Foram 26 votos pela rejeição da PEC na CCJ, e nenhum contrário.", "bli-ccj"),
        ],
        "inPractice": [
            ("Regra parecida valeu de 1988 até 2001, quando a Emenda Constitucional 35 acabou com a exigência de licença.",
             "Essa prerrogativa vigorou de 1988 até 2001.", "bli-ccj"),
            ("Hoje o parlamentar já não pode ser punido por opiniões, palavras e votos, e a Casa pode suspender processos que considerar abusivos.",
             "O exercício do mandato já é suficientemente protegido pela Constituição, com a imunidade material e o direito da Casa Legislativa de sustar os processos que entender abusivos.", "bli-ccj"),
        ],
        "argsFor": [
            ("O relator na Câmara, Claudio Cajado, disse que as prerrogativas são garantias para o parlamentar trabalhar com independência, sem temer perseguições.",
             "Segundo Cajado, as imunidades previstas na Constituição são indispensáveis para congressistas exercerem suas atribuições com independência, sem temer perseguições políticas ou intimações.", "bli-camara"),
            ("O deputado Carlos Jordy (PL-RJ) disse que o texto protege deputados de \"processo criminal abusivo\", muitas vezes por suas falas.",
             "Já o deputado Carlos Jordy (PL-RJ), vice-líder da Minoria , afirmou que o texto da PEC está longe do ideal, mas protege deputados de \"processo criminal abusivo\"", "bli-camara"),
        ],
        "argsAgainst": [
            ("O relator no Senado, Alessandro Vieira, disse que a PEC abriria as portas do Legislativo para \"criminosos de todos os tipos\".",
             "Configura-se em portas abertas para a transformação do Legislativo em abrigo seguro para criminosos de todos os tipos — disse o relator.", "bli-ccj"),
            ("O deputado Kim Kataguiri (União-SP) lembrou que, quando a licença existia, nenhuma investigação foi autorizada.",
             "Durante o período da Constituição de 1988, quando o texto que querem aprovar agora estava em vigor, nenhuma investigação foi autorizada", "bli-camara"),
        ],
        "nuance": [
            ("Há um meio-termo defendido por alguns: proteger só opiniões e votos. O senador Sergio Moro foi contra a PEC, mas defendeu reforçar a proteção para crimes contra a honra.",
             "O senador defendeu que a abrangência da proteção seja somente para crimes contra a honra", "bli-ccj"),
            ("O voto secreto para decidir a licença também dividiu os deputados e acabou retirado do texto na Câmara.",
             "No começo da madrugada desta quarta, o Plenário rejeitou, por insuficiência de quórum, a exigência de votação secreta", "bli-camara"),
        ],
    },
    "seg-armas": {
        "whatItIs": [
            ("O Estatuto do Desarmamento (Lei 10.826/2003) controla quem pode comprar e portar armas. Os detalhes são definidos por decretos do presidente, por isso as regras mudam a cada governo.",
             "O decreto regulamenta o Estatuto do Desarmamento ( Lei 10.826, de 2003 )", "arm-pdl"),
            ("Em 2023, o Decreto 11.615 restringiu o acesso: passou a fiscalização do Exército para a Polícia Federal e limitou os CACs (caçadores, atiradores e colecionadores).",
             "transferiu do Comando do Exército para a Polícia Federal a competência para fiscalização do registro de armas. Também reduziu a validade dos Certificados de Registros de Armas de Fogo e restringiu a atividade dos caçadores, atiradores e colecionadores (CACs).", "arm-pdl"),
        ],
        "inPractice": [
            ("Segundo pesquisadora da Secretaria Nacional de Segurança Pública, as armas particulares passaram de cerca de 1,3 milhão em 2018 para quase 3 milhões em 2023.",
             "Salta de cerca de 1,3 milhão para quase 3 milhões de armas", "arm-ccj"),
            ("O número de CACs registrados foi de cerca de 60 mil em 2017 para mais de 800 mil em 2022, segundo o policial federal e pesquisador Roberto Uchôa.",
             "Nós tínhamos, em 2017, cerca de 60 mil CACs registrados em todo o Brasil. A gente fecha 2022 com mais de 800 mil CACs registrados.", "arm-ccj"),
        ],
        "argsFor": [
            ("O senador Marcio Bittar (PL-AC), relator de projetos para derrubar o decreto de 2023, disse que ele limita o tiro desportivo e traz perdas a fabricantes e comerciantes.",
             "Ele afirma que o Decreto 11.615 contém “vícios” que, entre outros aspectos, limitam a prática do tiro desportivo, trazem perdas a fabricantes e comerciantes de armas", "arm-pdl"),
            ("O senador Magno Malta argumentou que o processo para o cidadão ter arma exige testes psicológicos, antecedentes e prova de tiro.",
             "Você vai para uma escola [de tiro], você tem que se inscrever, tem seus documentos, tem psicólogos, tem psiquiatras, você faz teste psicológico, traz antecedentes criminais", "arm-ccj"),
        ],
        "argsAgainst": [
            ("Michele dos Ramos, da Secretaria Nacional de Segurança Pública, disse que o país ficou \"muito mais armado\" sem mecanismos de controle suficientes.",
             "O Brasil que chegou a 2023 é um país muito mais armado, nós temos hoje em mãos civis mais do que o dobro de armas particulares que havia em 2018.", "arm-ccj"),
            ("Carolina Taboada, do Instituto Igarapé, apontou que só 2,3% dos acervos de CACs e clubes foram fiscalizados em 2020 e que armas com registro vencido escapam do controle.",
             "em 2020, somente 2,3% dos arcervos de CACs, clubes e entidades de tiros foram fiscalizados", "arm-ccj"),
        ],
        "nuance": [
            ("Há posições no meio: o policial federal e pesquisador Roberto Uchôa não fala em proibir, mas aponta que muitos viraram CAC como forma de circular armados sem ter porte.",
             "e viam na possibilidade de se tornar CAC uma forma de circularem armados.", "arm-ccj"),
            ("Parte da disputa é sobre quem decide: autores de projetos no Senado dizem que o decreto de 2023 foi além do que um decreto pode fazer, e o tema também passa pelo Congresso.",
             "Para os autores dos projetos, o decreto teria ido além da competência regulamentar do Poder Executivo.", "arm-pdl"),
        ],
    },
    "seg-maioridade": {
        "whatItIs": [
            ("Hoje quem tem menos de 18 anos não responde a processo criminal. Cumpre medidas socioeducativas do ECA (Estatuto da Criança e do Adolescente), com internação de no máximo três anos.",
             "Atualmente, jovens que cometem infrações graves cumprem medidas socioeducativas de internação por, no máximo, três anos.", "mai-2026"),
            ("Em 2015, a Câmara aprovou a PEC 171/1993, que reduz a maioridade para 16 anos em crimes hediondos, homicídio doloso e lesão corporal seguida de morte.",
             "a maioridade será reduzida nos casos de crimes hediondos – como estupro e latrocínio – e também para homicídio doloso e lesão corporal seguida de morte.", "mai-2015"),
        ],
        "inPractice": [
            ("Pela PEC de 2015, jovens de 16 e 17 anos cumpririam pena em local separado dos adolescentes e dos adultos.",
             "os jovens de 16 e 17 anos deverão cumprir a pena em estabelecimento separado dos adolescentes que cumprem medidas socioeducativas e dos maiores de 18 anos.", "mai-2015"),
            ("Uma alternativa aprovada no Senado em 2025 não mexe na maioridade: aumenta a internação de 3 para até 5 anos, ou até 10 em crimes violentos.",
             "O Senado aprovou em outubro do ano passado o projeto de lei que aumenta de três para até cinco anos o tempo máximo de internação de adolescentes infratores.", "mai-senado"),
        ],
        "argsFor": [
            ("O deputado Mendonça Filho (PL-PE) defendeu a redução como \"demanda de mais de 80% da população para crimes violentos\".",
             "O deputado Mendonça Filho (PL-PE) defendeu a redução, afirmando que “é uma demanda de mais de 80% da população para crimes violentos”.", "mai-2026"),
            ("O deputado Rogério Rosso disse que o jovem que comete crime grave \"sabe exatamente o que está fazendo\".",
             "Esse jovem que hoje tem permissão e licença para matar sabe exatamente o que está fazendo.", "mai-2015"),
        ],
        "argsAgainst": [
            ("A deputada Talíria Petrone (Psol-RJ) disse que só 8% dos atos de jovens são graves e que a prisão comum facilita o recrutamento pelo crime organizado.",
             "Já a deputada Talíria Petrone (Psol-RJ) criticou a proposta, argumentando que apenas 8% dos atos de jovens são graves e que o sistema prisional comum pode facilitar o recrutamento de adolescentes pelo crime organizado.", "mai-2026"),
            ("O deputado Darcísio Perondi disse que a Câmara decidiu \"pela emoção\" e que o pacote contra a violência \"não será entregue\".",
             "“Está se vendendo um pacote contra a violência que não será entregue à população”, avaliou Perondi.", "mai-2015"),
        ],
        "nuance": [
            ("As propostas variam muito: algumas reduzem só para crimes hediondos, outras para todos os crimes, e uma chega a 12 anos em crimes violentos.",
             "Já a PEC 9/26, da deputada Julia Zanatta (PL-SC), propõe a redução geral para 16 anos em todos os crimes e estabelece que adolescentes de 12 a 16 anos também respondam criminalmente", "mai-2026"),
            ("Quem quer punição maior sem mudar a Constituição pode preferir aumentar o tempo de internação, como no projeto do senador Fabiano Contarato.",
             "Não estamos falando em redução de maioridade penal, estamos ampliando, mantendo...", "mai-senado"),
        ],
    },
    "seg-stf-mandato": {
        "whatItIs": [
            ("Hoje os ministros do STF ficam no cargo até a aposentadoria obrigatória aos 75 anos. É a vitaliciedade, garantia que a Constituição dá aos juízes.",
             "Para ele, o mandato vitalício com aposentadoria compulsória aos 75 anos — conforme a regra atual — dá muito poder aos ministros.", "stf-pec"),
            ("A PEC 16/2019, do senador Plínio Valério, fixa mandato de oito anos sem recondução. Outras propostas falam em 10, 11 ou 15 anos.",
             "Ou 11, da PEC 342/2009 , do então deputado federal Flávio Dino; ou 15, da PEC 51/2023 , que o senador Flávio Arns apresentou.", "stf-plinio"),
        ],
        "inPractice": [
            ("A PEC de Plínio também dá prazo para o presidente indicar (um mês) e para o Senado votar (120 dias) quando abre uma vaga.",
             "o presidente terá até um mês, a contar do surgimento da vaga no STF, para indicar ao Senado o nome de um novo ministro. E então o Senado teria até 120 dias para analisar a indicação.", "stf-pec"),
            ("Com mandato fixo, as trocas ficariam mais previsíveis. Hoje um presidente pode indicar vários ministros num só ano, como em 2023.",
             "Em 2023, por exemplo, serão abertas duas novas vagas no Supremo Tribunal Federal", "stf-pec"),
        ],
        "argsFor": [
            ("O senador Plínio Valério argumentou que mandatos fixos evitam mudanças bruscas na composição do tribunal e a consequente insegurança.",
             "evitaria mudanças significativas na composição do STF em um curto espaço de tempo, com alterações súbitas de entendimento e consequente insegurança institucional.", "stf-pec"),
            ("O então senador Eduardo Suplicy defendeu, em 2009, que mandato fixo não fere a independência do Judiciário e permite renovação planejada.",
             "a proposta não feria a garantia de independência do Judiciário ao fixar prazo de oito anos de mandato para desembargadores e ministros dos tribunais superiores e de dez anos para ministros do STF.", "stf-ccj2009"),
        ],
        "argsAgainst": [
            ("O então senador Demóstenes Torres argumentou que a Constituição não permite nem recomenda mandato temporário, por ser a vitaliciedade uma prerrogativa dos juízes.",
             "Demóstenes ponderou, entretanto, não ser possível nem conveniente - pelos termos da Constituição - estabelecer mandato temporário para esses cargos.", "stf-ccj2009"),
            ("O então senador Aloizio Mercadante disse que a mudança interfere na relação entre os Poderes e exigiria ampla discussão com o Judiciário.",
             "Na sua avaliação, as mudanças propostas interferem nas relações entre os Poderes da República e, portanto, não poderiam ser aprovadas sem passar por uma ampla discussão com o Judiciário.", "stf-ccj2009"),
        ],
        "nuance": [
            ("A ideia não divide só esquerda e direita: segundo Plínio Valério, cinco ministros do próprio STF demonstraram apoio a discutir o tema.",
             "Segundo ele, 5 dos 11 ministros demonstraram apoio a essa discussão", "stf-plinio"),
            ("Concordar com mandato fixo não diz nada sobre o tamanho do mandato, nem se valeria para os ministros atuais. Plínio afirma que a PEC não pretende atingi-los.",
             "Plínio ainda observou que a fixação do mandato não tem como objetivo atingir ministros atuais", "stf-plinio"),
        ],
    },
}

TOPICS = {
    "seg-saidinha": ["saída temporária", "saidinha", "saidão", "saídas temporárias"],
    "seg-drogas": ["droga", "entorpecente", "maconha"],
    "seg-8-janeiro": ["8 de janeiro", "dosimetria", "golpe"],
    "seg-blindagem": ["PEC", "parlamentar", "prerrogativa", "blindagem"],
    "seg-armas": ["arma", "CAC", "desarmamento"],
    "seg-maioridade": ["maioridade"],
    "seg-stf-mandato": ["STF", "Supremo", "vitalic", "mandato"],
}
