"""Explainers for the Paraíba questions. Arguments come from people outside the 2026 PB ballot."""

SOURCES = {
    "ppp-lei": ("https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2004/lei/l11079.htm", "Lei 11.079/2004 (Lei das PPPs), Planalto"),
    "estatais": ("https://www12.senado.leg.br/noticias/infomaterias/2023/02/privatizacao-desmonte-do-estado-ou-modernizacao-de-empresas-ineficientes",
                 "Agência Senado, especial de 02/2023"),
    "san-aprova": ("https://www12.senado.leg.br/noticias/materias/2020/06/24/senado-aprova-novo-marco-legal-do-saneamento-basico",
                   "Agência Senado, 24/06/2020"),
    "san-debate": ("https://www12.senado.leg.br/noticias/materias/2020/06/24/para-a-maioria-dos-senadores-o-novo-marco-legal-vai-melhorar-o-saneamento-basico-no-pais",
                   "Agência Senado, 24/06/2020"),
    "cagepa": ("https://movimentoeconomico.com.br/saneamento/2026/05/15/acciona-vence-ppp-da-cagepa-com-r-3-bilhoes-e-unico-lance-na-b3/",
               "Movimento Econômico, 15/05/2026"),
    "icms-cons": ("https://www12.senado.leg.br/noticias/materias/2013/03/11/isencoes-do-icms-na-guerra-fiscal-afetam-a-produtividade-da-economia-no-longo-prazo-diz-consultor",
                  "Agência Senado, 11/03/2013"),
    "icms-2032": ("https://www12.senado.leg.br/noticias/materias/2021/10/06/aprovado-projeto-que-prorroga-incentivos-fiscais-a-empresas-por-ate-15-anos",
                  "Agência Senado, 06/10/2021"),
    "rt-senado": ("https://www12.senado.leg.br/noticias/materias/2023/11/08/senado-aprova-reforma-tributaria-no-primeiro-turno-no-plenario",
                  "Agência Senado, 08/11/2023"),
    "cf": ("https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm", "Constituição Federal, Planalto"),
    "pm-pec": ("https://www12.senado.leg.br/institucional/datasenado/materias/enquetes/desmilitarizacao-da-pm", "DataSenado, enquete sobre a PEC 51/2013"),
    "pm-lind": ("https://www12.senado.leg.br/noticias/materias/2014/03/20/lindberg-farias-defende-proposta-de-reformulacao-da-policia",
                "Agência Senado, 20/03/2014"),
    "pm-cam": ("https://www.camara.leg.br/noticias/486465-desmilitarizacao-da-policia-divide-opinioes-em-audiencia-publica-na-camara/",
               "Agência Câmara, audiência pública"),
    "cac-pauta": ("https://sapl.al.pb.leg.br/media/sapl/public/sessaoplenaria/1187/pauta/1187_pauta_sessao.pdf", "ALPB, pauta da sessão de 14/02/2023"),
    "arm-ccj": ("https://www12.senado.leg.br/noticias/materias/2023/04/19/senadores-e-especialistas-divergem-sobre-regras-para-uso-de-armas",
                "Agência Senado, 19/04/2023"),
    "arm-pdl": ("https://www12.senado.leg.br/noticias/materias/2026/02/20/csp-vota-projetos-para-derrubar-decreto-que-restringiu-acesso-a-armas",
                "Agência Senado, 20/02/2026"),
    "ns-pauta": ("https://sapl.al.pb.leg.br/media/sapl/public/sessaoplenaria/1350/pauta/ordem_do_dia_23.09.2025_3a_sessao_ordinaria_itinerante.pdf",
                 "ALPB, ordem do dia de 23/09/2025"),
    "ns-decreto": ("https://agenciabrasil.ebc.com.br/direitos-humanos/noticia/2016-04/publicado-decreto-que-autoriza-nome-social-de-travestis-no-servico",
                   "Agência Brasil, 29/04/2016"),
    "ns-senado": ("https://www12.senado.leg.br/institucional/responsabilidade-social/equidade/equidade-eventos/retificacao-do-registro-e-nome-social-sao-conquistas-da-comunidade-trans",
                  "Senado Federal, Equidade"),
    "ns-ovando": ("https://www.camara.leg.br/noticias/1143419-projeto-suspende-uso-de-nome-social-em-concurso/", "Agência Câmara, 2025"),
    "vs-guedes": ("https://agenciabrasil.ebc.com.br/saude/noticia/2020-10/jamais-esteve-sob-analise-privatizar-o-sus-diz-guedes",
                  "Agência Brasil, 29/10/2020"),
    "vs-sus": ("https://www12.senado.leg.br/noticias/materias/2018/08/13/incentivo-fiscal-e-politica-de-precos-de-planos-de-saude-agravam-a-situacao-dos-sus-dizem-debatedores",
               "Agência Senado, 13/08/2018"),
}

EXPLAINERS = {
    "pb-concessoes-ppp": {
        "whatItIs": [
            ("Concessão é quando o governo passa uma obra ou serviço para uma empresa operar por contrato. PPP (parceria público-privada) é um tipo de concessão em que o governo também paga parte da remuneração da empresa.",
             "Concessão patrocinada é a concessão de serviços públicos ou de obras públicas de que trata a Lei nº 8.987, de 13 de fevereiro de 1995, quando envolver, adicionalmente à tarifa cobrada dos usuários contraprestação pecuniária do parceiro público ao parceiro privado.", "ppp-lei"),
            ("Na PPP administrativa, o próprio governo é o usuário do serviço e paga por ele, mesmo que a empresa também construa a obra.",
             "Concessão administrativa é o contrato de prestação de serviços de que a Administração Pública seja a usuária direta ou indireta, ainda que envolva execução de obra ou fornecimento e instalação de bens.", "ppp-lei"),
        ],
        "inPractice": [
            ("Concessão não é venda: a empresa continua sendo do governo, ou o serviço continua público, mas a operação passa a uma empresa privada por prazo definido.",
             "Privatização, hoje em dia, não é apenas vender os ativos de uma empresa estatal, mas também trazer o investidor privado para fazer coisas que o setor público antes fazia, seja por meio de parcerias público-privadas, seja por meio de concessões.", "estatais"),
            ("Em 2026 a Paraíba passou a uma empresa privada, por PPP de 25 anos, o esgoto de 85 cidades atendidas pela Cagepa.",
             "O contrato, com prazo de 25 anos, prevê R$ 3 bilhões em investimentos.", "cagepa"),
        ],
        "argsFor": [
            ("O economista Armando Castelar (FGV) argumenta que o poder público não tem dinheiro para tantas obras e que, nos contratos com empresas, o serviço não pode parar.",
             "Nos contratos com a iniciativa privada, os serviços não podem parar.", "estatais"),
            ("O consultor do Senado Pedro Fernando Nery lembra que, com uma agência reguladora forte, o governo mantém poder para exigir obrigações sociais das empresas.",
             "As agências reguladoras, como a das telecomunicações (Anatel), a da energia elétrica (Aneel) e a das águas e saneamento básico (ANA), têm poderes para impor sanções aos grupos empresariais que não cumpram com suas obrigações sociais.", "estatais"),
        ],
        "argsAgainst": [
            ("No debate do marco do saneamento, o senador Weverton disse que o investimento privado tende a ficar nas grandes cidades e não chegar às pequenas do Norte e Nordeste.",
             "Sabemos que, infelizmente quanto às cidades pequenas, principalmente do Norte e do Nordeste, esses investimentos não vão chegar, como foi aqui falado.", "san-debate"),
            ("O senador Rogério Carvalho avaliou que abrir o setor pode desvalorizar as empresas públicas e prejudicar o patrimônio delas.",
             "Em sua avaliação, as mudanças previstas pelo projeto poderão gerar desvalorização das empresas públicas de saneamento, o que pode prejudicar o patrimônio dessas estatais.", "san-debate"),
        ],
        "nuance": [
            ("Especialistas ouvidos pelo Senado dizem que o tema ficou menos ideológico: a esquerda aceita concessões e a direita aceita algumas estatais.",
             "Enquanto a esquerda agora aceita que empresas privadas prestem certos serviços públicos à população, a direita admite que o governo permaneça comandando determinadas empresas.", "estatais"),
            ("Concessões também dão problema: o consultor Pedro Nery cita concessionária de aeroporto que pediu para devolver a operação ao governo.",
             "As concessões de aeroportos, por exemplo, têm enfrentado problemas.", "estatais"),
        ],
    },
    "pb-ppp-cagepa": {
        "whatItIs": [
            ("Em 15/05/2026, o grupo espanhol Acciona venceu o leilão da PPP de esgoto da Cagepa, a companhia estadual de água e esgoto da Paraíba.",
             "O grupo espanhol Acciona venceu nesta sexta-feira (15) o leilão da Parceria Público-Privada (PPP) de esgotamento sanitário da Companhia de Água e Esgotos da Paraíba ( Cagepa )", "cagepa"),
            ("O contrato cobre 85 municípios, incluindo João Pessoa, dura 25 anos e prevê R$ 3 bilhões em investimentos.",
             "O contrato, com prazo de 25 anos, prevê R$ 3 bilhões em investimentos.", "cagepa"),
        ],
        "inPractice": [
            ("A água continua com a Cagepa, que também fiscaliza a parceria. A empresa privada cuida da coleta e do tratamento de esgoto.",
             "O abastecimento de água segue integralmente sob responsabilidade da Cagepa , que também permanecerá responsável pela gestão e fiscalização da parceria.", "cagepa"),
            ("Hoje o esgoto urbano atende 6,71% no Alto Piranhas e 46,43% no Litoral. A meta é chegar a 90% até 2039.",
             "Os índices atuais de atendimento de esgoto urbano nas microrregiões são de 6,71% no Alto Piranhas e 46,43% no Litoral .", "cagepa"),
            ("Só uma empresa deu lance, com desconto de 1% sobre o valor máximo que o estado aceitava pagar.",
             "A empresa foi a única a apresentar proposta no certame paraibano e ofereceu deságio de 1% sobre a contraprestação pública máxima fixada em edital.", "cagepa"),
        ],
        "argsFor": [
            ("O presidente da Cagepa, Marcus Vinícius, disse que a parceria dá à companhia sustentabilidade financeira e mais capacidade de investir.",
             "Essa parceria representa uma virada de chave para a Cagepa e para o estado, garantindo sustentabilidade financeira, fortalecimento da governança", "cagepa"),
            ("Luciene Machado, do BNDES, que estruturou o projeto, disse que o modelo transforma investimentos em benefícios concretos.",
             "É um modelo capaz de transformar investimentos em benefícios concretos para a população", "cagepa"),
        ],
        "argsAgainst": [
            ("Críticos do modelo nacional, como o senador Weverton, dizem que o investimento privado em saneamento tende a não chegar às cidades pequenas.",
             "É um projeto que vai beneficiar os grandes centros, claro, onde as grandes empresas têm interesse de investir", "san-debate"),
            ("O senador Rogério Carvalho avaliou que a entrada de empresas privadas pode desvalorizar as estatais de saneamento.",
             "Em sua avaliação, as mudanças previstas pelo projeto poderão gerar desvalorização das empresas públicas de saneamento", "san-debate"),
        ],
        "nuance": [
            ("A PPP é consequência do marco nacional do saneamento de 2020, que obriga licitação aberta a empresas públicas e privadas e fixa metas de universalização.",
             "O texto também torna obrigatória a abertura de licitação, envolvendo empresas públicas e privadas.", "san-aprova"),
            ("O prazo da Paraíba (2039) é mais longo que o padrão do marco nacional (2033), por decisão do colegiado regional para segurar a tarifa.",
             "O prazo-padrão do Novo Marco Legal do Saneamento (Lei 14.026/2020) é 2033 .", "cagepa"),
        ],
    },
    "pb-incentivos-fiscais": {
        "whatItIs": [
            ("Incentivo fiscal é quando o estado cobra menos ICMS de uma empresa para atrair investimento para seu território.",
             "mediante concessões de isenções fiscais para atrair o investimento produtivo das empresas", "icms-cons"),
            ("Quando vários estados fazem isso ao mesmo tempo, disputando empresas, chama-se guerra fiscal.",
             "A guerra fiscal é resultado da concessão unilateral de isenções e benefícios fiscais do ICMS por parte de estados que buscam atrair investimentos para seus territórios.", "icms-2032"),
        ],
        "inPractice": [
            ("Uma lei de 2021 permitiu prorrogar esses benefícios até 2032.",
             "que prorroga até 2032 incentivos fiscais concedidos pelos estados e pelo Distrito Federal para empresas no âmbito da guerra fiscal", "icms-2032"),
            ("A reforma tributária muda a cobrança para o estado onde o produto é consumido, o que reduz a força desses incentivos a partir da transição.",
             "A mudança visa dar fim à chamada guerra fiscal — a concessão de benefícios tributários por estados com o objetivo de atrair investimentos.", "rt-senado"),
        ],
        "argsFor": [
            ("A senadora Rose de Freitas, relatora da prorrogação, argumentou que o incentivo não é perda de receita, porque sem ele a empresa nem viria para o estado.",
             "A concessão de incentivos fiscais não constitui renúncia de receitas (fiscal), visto que os Estados nunca tiveram a receita correspondente", "icms-2032"),
            ("Segundo o consultor do Senado Márcio de Oliveira Júnior, para estados menos desenvolvidos o incentivo gera emprego e renda locais.",
             "por um lado, produz benefícios locais em termos de geração de emprego e renda", "icms-cons"),
        ],
        "argsAgainst": [
            ("O mesmo consultor, Márcio de Oliveira Júnior, diz que o uso generalizado prejudica a produtividade do país e que a maior beneficiada é a empresa.",
             "gera efeitos deletérios sobre a produtividade da economia no longo prazo, inclusive por conta da incerteza jurídica advinda de benefícios fiscais concedidos ao arrepio da lei", "icms-cons"),
            ("O senador José Aníbal chamou a guerra fiscal de \"uma corrida para o fundo\".",
             "São Paulo está sempre na mira dos subsídios e da guerra fiscal, que é uma corrida para o fundo, não é para a frente e nem para o alto.", "icms-2032"),
        ],
        "nuance": [
            ("A pergunta inclui uma condição: manter o incentivo cobrando metas de investimento e emprego. Segundo o consultor, o ganho do estado vem justamente dos empregos criados pela empresa que se instala.",
             "Já o estado concedente da isenção, teria algum ganho na criação de novos postos de trabalho decorrentes da instalação da nova empresa", "icms-cons"),
            ("Para o consultor, o ganho para a população do próprio estado tende a ser menor que o da empresa beneficiada.",
             "mas para o país como um todo — e mesmo para o conjunto da população do estado — o benefício seria consideravelmente menor", "icms-cons"),
        ],
    },
    "pb-desmilitarizar-pm": {
        "whatItIs": [
            ("Pela Constituição, as polícias militares são forças auxiliares e reserva do Exército e ficam sob o comando dos governadores.",
             "As polícias militares e corpos de bombeiros militares, forças auxiliares e reserva do Exército, subordinam-se, juntamente com as polícias civis, aos Governadores dos Estados", "cf"),
            ("Desmilitarizar é transformar a PM em polícia civil, sem a estrutura e a justiça militares. A proposta mais conhecida é a PEC 51/2013.",
             "O texto prevê ainda que os estados organizem suas polícias em carreira única, ao passo que define a polícia como instituição de natureza civil.", "pm-pec"),
        ],
        "inPractice": [
            ("Como o caráter militar das PMs está na Constituição, mudá-lo exige uma emenda constitucional votada no Congresso. O governador comanda a PM, mas não a desmilitariza sozinho.",
             "O tema da enquete é apenas uma das mudanças contidas na proposta de emenda à Constituição ( PEC 51/2013 )", "pm-pec"),
            ("A PEC 51 também prevê o \"ciclo completo\": a mesma polícia patrulharia e investigaria, tarefas hoje divididas entre PM e Polícia Civil.",
             "Dispõe também sobre o chamado “ciclo completo” da atividade policial", "pm-pec"),
        ],
        "argsFor": [
            ("A defensora pública Fernanda Rudolfo disse que treinar policiais com \"visão de guerra\" para lidar com civis não cabe num estado democrático.",
             "Até porque se tem um treinamento militar para lidar com civis, para enfrentar questões ligadas ao povo com um treinamento com uma visão de guerra.", "pm-cam"),
            ("O autor da PEC, então senador Lindbergh Farias, citou pesquisa da FGV segundo a qual 74% dos brasileiros não confiam nas polícias.",
             "pesquisa da Fundação Getúlio Vargas (FGV) revelou que 74% dos brasileiros não confiam nas polícias.", "pm-lind"),
        ],
        "argsAgainst": [
            ("O deputado Subtenente Gonzaga (PDT-MG) argumentou que o problema não é a militarização, e sim a violência da sociedade, que qualquer polícia enfrentaria.",
             "Já o deputado Subtenente Gonzaga (PDT-MG) defende que o problema da PM não é a militarização porque, segundo ele, as outras polícias têm hierarquias semelhantes.", "pm-cam"),
            ("Uma cidadã que comentou a proposta no DataSenado, Elzana de Oliveira Moreira Moraes, defendeu que o militarismo \"impõe respeito\" e ajuda a manter a ordem.",
             "“o militarismo impõe respeito, não é autoritarismo.", "pm-pec"),
        ],
        "nuance": [
            ("Há quem apoie a mudança devagar: o deputado Delegado Edson Moreira defendeu desmilitarizar de forma gradual, sem prejudicar a carreira dos policiais.",
             "acredita que a desmilitarização das polícias é necessária, mas deve ser feita de forma gradual, sem prejuízo para a carreira dos policiais.", "pm-cam"),
            ("Numa enquete do DataSenado (sem valor científico), 54% foram contra e 46% a favor.",
             "Ao todo, 54% dos votos foram contrários à mudança e 46%, a favor.", "pm-pec"),
        ],
    },
    "pb-cac-arma": {
        "whatItIs": [
            ("CAC é a sigla para caçadores, atiradores desportivos e colecionadores de armas, que têm registro próprio.",
             "restringiu a atividade dos caçadores, atiradores e colecionadores (CACs).", "arm-pdl"),
            ("Um projeto aprovado na Assembleia da Paraíba \"reconhece o risco da atividade\" e a necessidade de arma para atiradores esportivos. O governador vetou o projeto por inconstitucionalidade.",
             "Reconhece o risco da atividade e a efetiva necessidade do aporte de arma de fogo aos atiradores desportivos integrantes de entidades legalmente constituídas no âmbito do Estado da Paraíba", "cac-pauta"),
        ],
        "inPractice": [
            ("Regras de armas são federais: o Estatuto do Desarmamento é uma lei nacional regulamentada por decreto do presidente. Por isso o veto alegou inconstitucionalidade.",
             "RAZÕES DO VETO: INCONSTITUCIONALIDADE", "cac-pauta"),
            ("O número de CACs saltou de cerca de 60 mil em 2017 para mais de 800 mil em 2022, segundo o pesquisador Roberto Uchôa.",
             "Nós tínhamos, em 2017, cerca de 60 mil CACs registrados em todo o Brasil. A gente fecha 2022 com mais de 800 mil CACs registrados.", "arm-ccj"),
        ],
        "argsFor": [
            ("O senador Magno Malta argumentou que tirar o registro exige escola de tiro, testes psicológicos e antecedentes criminais.",
             "Você vai para uma escola [de tiro], você tem que se inscrever, tem seus documentos, tem psicólogos, tem psiquiatras, você faz teste psicológico, traz antecedentes criminais", "arm-ccj"),
            ("O senador Marcio Bittar disse que as restrições federais limitam o tiro desportivo e trazem perdas ao setor.",
             "Ele afirma que o Decreto 11.615 contém “vícios” que, entre outros aspectos, limitam a prática do tiro desportivo", "arm-pdl"),
        ],
        "argsAgainst": [
            ("O pesquisador Roberto Uchôa disse que muitos se tornaram CAC para circular armados sem conseguir porte na Polícia Federal.",
             "Eram pessoas que não estavam conseguindo o porte de arma pela Polícia Federal, seja porque não tinham razões para tal, seja porque não conseguiam justificar essa necessidade", "arm-ccj"),
            ("Carolina Taboada, do Instituto Igarapé, apontou que só 2,3% dos acervos de CACs e clubes foram fiscalizados em 2020.",
             "em 2020, somente 2,3% dos arcervos de CACs, clubes e entidades de tiros foram fiscalizados", "arm-ccj"),
        ],
        "nuance": [
            ("Na Assembleia, votar SIM num veto derruba o veto e aprova o projeto; votar NÃO mantém o veto. Por isso o voto de cada deputado num veto também reflete sua relação com o governo estadual.",
             "VOTANDO SIM O DEPUTADO REJEITA O VETO, APROVANDO O PROJETO, E VOTANDO NÃO, ACEITA O VETO, REJEITANDO O PROJETO", "cac-pauta"),
            ("Mesmo entre críticos da flexibilização, há quem aceite o tiro esportivo e mire só o uso do registro de CAC como atalho para o porte.",
             "e viam na possibilidade de se tornar CAC uma forma de circularem armados.", "arm-ccj"),
        ],
    },
    "pb-nome-social": {
        "whatItIs": [
            ("Nome social é o nome pelo qual uma pessoa travesti ou transexual se identifica e é reconhecida, diferente do nome no registro civil.",
             "o nome social configura a designação pela qual a pessoa se identifica e é socialmente reconhecida", "ns-decreto"),
            ("Desde 2016 um decreto obriga órgãos federais a usar o nome social quando a pessoa pede.",
             "deverão adotar o nome social da pessoa travesti ou transexual, de acordo com seu requerimento e com o disposto neste decreto", "ns-decreto"),
        ],
        "inPractice": [
            ("O projeto da Assembleia da Paraíba permitiria incluir o nome social nas contas e comunicações das concessionárias de água, luz e gás. O governador vetou o projeto.",
             "Dispõe sobre a possibilidade de inclusão do nome social dos consumidores nas comunicações realizadas pelas concessionárias estaduais de água, luz e gás encanado", "ns-pauta"),
            ("Desde 2018 é possível mudar nome e gênero direto no cartório, sem processo judicial, mas muita gente ainda não fez a retificação.",
             "publicou um normativo ( Provimento 73/2018 ) que passou a exigir que todos os cartórios de registro de pessoas do país realizassem a mudança, sem a necessidade de processo judicial.", "ns-senado"),
        ],
        "argsFor": [
            ("A Antra (Associação Nacional de Travestis e Transexuais) estima que ao menos 63,6% das pessoas trans ainda não conseguiram retificar os documentos, por custo e falta de informação.",
             "dados da Associação Nacional de Travestis e Transexuais (Antra) informam que pelos menos 63,6% dessas pessoas ainda não conseguiram a retificação", "ns-senado"),
            ("Lui Oliveira, servidor do Senado, contou que evitou usar o nome social por medo de discriminação até se sentir seguro.",
             "Enquanto estagiário, eu tive a possibilidade de já preencher o nome social no ato do cadastro, mas não o fiz pelo receio da discriminação.", "ns-senado"),
        ],
        "argsAgainst": [
            ("O deputado Dr. Luiz Ovando (PP-MS) argumentou que regras de nome social podem gerar tratamentos diferenciados e ferir a igualdade (isonomia).",
             "Dr. Luiz Ovando argumenta que a norma pode gerar desigualdades e ferir o princípio da isonomia.", "ns-ovando"),
            ("Luiz Ovando também disse que esse tipo de norma pode transformar a administração pública em \"espaço de militância política\".",
             "pode transformar a administração pública em um espaço de militância política, em vez de um local onde prevaleça a competência técnica e o mérito.", "ns-ovando"),
        ],
        "nuance": [
            ("O veto estadual citou inconstitucionalidade e interesse público, não só o mérito: parte da discussão é se o estado pode impor isso a concessionárias.",
             "RAZÕES DO VETO: INCONSTITUCIONALIDADE E CONTRÁRIO AO INTERESSE PÚBLICO", "ns-pauta"),
            ("Usar o nome social é opcional e não muda o registro civil: o nome do registro continua existindo para fins administrativos.",
             "Nesse caso, o nome do registro civil deve permanecer confidencial e ser utilizado somente com autorização da pessoa ou para fins estritamente necessários.", "ns-senado"),
        ],
    },
    "pb-vale-saude": {
        "whatItIs": [
            ("A ideia de um vale-saúde (ou voucher) é dar ao paciente um crédito público para ser atendido num hospital particular, em vez de esperar na rede pública.",
             "o governo ofereceria aos usuários um voucher para atendimento médico na rede privada, para suplementar o setor de saúde pública.", "vs-guedes"),
            ("A Constituição já permite que hospitais privados atendam pelo SUS de forma complementar, por contrato ou convênio, com preferência para filantrópicos.",
             "As instituições privadas poderão participar de forma complementar do sistema único de saúde, segundo diretrizes deste, mediante contrato de direito público ou convênio, tendo preferência as entidades filantrópicas e as sem fins lucrativos.", "cf"),
        ],
        "inPractice": [
            ("A mesma Constituição proíbe dar dinheiro público como auxílio ou subvenção a instituições privadas com fins lucrativos. Um vale teria de caber nessas regras.",
             "É vedada a destinação de recursos públicos para auxílios ou subvenções às instituições privadas com fins lucrativos.", "cf"),
            ("Em 2020, o governo federal chegou a incluir postos de saúde no programa de parcerias com empresas, mas revogou a medida depois da repercussão.",
             "Diante das repercussões, ontem (28), a medida foi revogada", "vs-guedes"),
        ],
        "argsFor": [
            ("O então ministro da Economia, Paulo Guedes, defendeu um \"voucher saúde\" dizendo que o paciente atendido na rede privada fica melhor do que sem atendimento.",
             "Aí a pessoa vai ser atendida, é melhor do que não ter [atendimento]”, disse", "vs-guedes"),
            ("Guedes argumentou que o setor público sozinho não tem capacidade financeira para atender todo mundo.",
             "porque o setor público sozinho não tem a capacidade financeira de atender todo mundo", "vs-guedes"),
        ],
        "argsAgainst": [
            ("Christine Alves, da Escola Nacional de Saúde Pública (ENSP/Fiocruz), disse que as ineficiências do Estado não justificam transferir recursos ao setor privado.",
             "De acordo com ela, as ineficiências do Estado na saúde pública não podem ser utilizadas como justificativa para a política de renúncia fiscal ao setor privado.", "vs-sus"),
            ("Para Christine Alves, mesmo com estímulo do governo, os planos privados não reduziram a demanda sobre o SUS.",
             "Para Christine Alves, apesar de todo o estímulo do governo, os planos de saúde não auxiliam na redução da demanda ao Sistema Único de Saúde (SUS).", "vs-sus"),
        ],
        "nuance": [
            ("Mesmo defensores do voucher dizem não querer acabar com o SUS: Guedes chamou de \"contrassenso\" privatizar o sistema durante a pandemia.",
             "e que seria um contrassenso a privatização", "vs-guedes"),
            ("A diferença entre vale-saúde e convênio é quem escolhe: no convênio o SUS escolhe e contrata o hospital; no vale, o paciente escolhe entre os credenciados.",
             "mediante contrato de direito público ou convênio", "cf"),
        ],
    },
    "pb-empresas-publicas": {
        "whatItIs": [
            ("Empresa pública (estatal) é uma empresa controlada pelo governo. No Brasil elas começaram a ser criadas em série nos anos 1940, como Petrobras, CSN e Vale.",
             "Estatais começaram a ser criadas em série no Brasil na década de 1940, no governo do presidente Getúlio Vargas.", "estatais"),
            ("Na Paraíba, a principal estatal é a Cagepa, que leva água a 201 dos 223 municípios.",
             "Atualmente, a companhia atende 201 dos 223 municípios paraibanos", "cagepa"),
        ],
        "inPractice": [
            ("Criar uma estatal exige lei e dinheiro do governo. Uma estatal precisa fazer concurso público para contratar e licitação para comprar, o que a deixa mais lenta que uma empresa privada.",
             "O que ocorre é que uma empresa privada não precisa carregar os vários pesos que uma empresa estatal é obrigada a carregar, como organizar concurso público para contratar pessoal e abrir licitação para fazer compras.", "estatais"),
            ("Governos de orientações diferentes já criaram estatais: o governo federal de 2019 a 2022, que vendia empresas, criou a NAV Brasil para controle aéreo.",
             "Nery lembra que até o governo Bolsonaro criou uma estatal, a NAV Brasil, vinculada à Aeronáutica e dedicada aos serviços de controle aéreo.", "estatais"),
        ],
        "argsFor": [
            ("O senador Paulo Paim defende explorar o potencial das estatais produtivas e diz que corrupção em casos isolados não justifica fechar empresas que dão lucro.",
             "Não se devem prejudicar cadeias produtivas inteiras e empresas que dão lucro, como é o caso da Petrobras.", "estatais"),
            ("Jean Paul Prates, ex-presidente da Petrobras, defendeu que há privatizações ruins e que vender refinarias penalizou o consumidor.",
             "Eu acredito que há privatizações boas e más, necessárias e totalmente desnecessárias.", "estatais"),
        ],
        "argsAgainst": [
            ("O economista Armando Castelar (FGV) diz que estatais eram necessárias quando faltava capital privado, o que não é mais o caso.",
             "Faz algum tempo que essa presença grande do poder público não é mais necessária e justificável — continua Castelar.", "estatais"),
            ("O senador Marcio Bittar avalia que raras empresas precisam ser do Estado e cita o uso político de indicações em estatais.",
             "A Petrobras mostrou o estrago que as indicações políticas para as estatais podem fazer.", "estatais"),
        ],
        "nuance": [
            ("O consultor do Senado Pedro Nery defende avaliar caso a caso: cada modelo, estatal ou privado, tem vantagens e desvantagens.",
             "O importante é saber que cada modelo, o estatal e o privado, tem vantagens e desvantagens. Nenhum é perfeito.", "estatais"),
            ("Para Castelar, uma estatal só se justifica se tiver papel social além do comercial, como cobrar mais dos ricos para subsidiar os pobres.",
             "hoje uma estatal só se justifica se cumprir algum papel social, além do comercial, como cobrar mais dos ricos de modo a subsidiar o serviço oferecido aos pobres.", "estatais"),
        ],
    },
}

TOPICS = {
    "pb-concessoes-ppp": ["concess", "parceria", "PPP", "privatiza", "saneamento"],
    "pb-ppp-cagepa": ["Cagepa", "saneamento", "esgoto"],
    "pb-incentivos-fiscais": ["incentivo", "isenç", "guerra fiscal", "ICMS"],
    "pb-desmilitarizar-pm": ["polícia", "militar", "PM"],
    "pb-cac-arma": ["arma", "atirador", "CAC"],
    "pb-nome-social": ["nome social"],
    "pb-vale-saude": ["saúde", "SUS", "voucher"],
    "pb-empresas-publicas": ["estata", "empresa"],
}
